### ISSUE TITLE
Support for Sparkasse [DE]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#100]
Sourced from [ma-ver-ick/ynab-converter](https://github.com/ma-ver-ick/ynab-converter/blob/master/sparkasse.py).

File layout:
_Sparkasse_
Auftragskonto, Buchungstag, Valutadatum, Buchungstext, Verwendungszweck, Beguenstigter/Zahlungspflichtiger, Kontonummer, BLZ, Betrag, Waehrung, Info

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

From Issue #21 master list

**Comment by nocalla** [comment]
Apparently this is a generic name for a bank and not a specific one. Closing. Will reopen if we can get actual reference for the bank!

**Comment by torbengb** [comment]
> Apparently this is a generic name for a bank and not a specific one.

I humbly disagree: https://www.sparkasse.de/ :-)

>

**Comment by torbengb** [comment]
You are right, it literally means "bank." But it's also the actual name of
an actual bank. Yeah, it's odd.
