### ISSUE TITLE
Support for Bancolombia [CO]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#106]
Sourced from [Asgaroth/ynab](https://github.com/Asgaroth/ynab).

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

From Issue #21 master list

**Comment by ricardopolo** [comment]
Is Bancolombia supported? I don't see it in the README

**Comment by nocalla** [comment]
Not currently, as we were unable to get sufficient information about the format. If you have the information, please fill it in here based off the list below. Leave anything you don't understand blank and if possible paste a few anonymised sample rows from the export file. 

To be filled in as required. Delete fields that match default values.
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

**Comment by nocalla** [comment]
I think we mostly just needed the file name of the bank export.

**Comment by nocalla** [comment]
Closing again until we get the filename.

**Comment by ricardopolo** [comment]
I just export a file and its name is `049-594671-16_118.qif`. They also support XLS,  Text and XML

**Comment by nocalla** [comment]
Is the text output a .CSV file?

**Comment by ricardopolo** [comment]
Yes, it's a CSV with this structure 
![image](https://user-images.githubusercontent.com/1263856/106787881-39d14480-661e-11eb-9f7d-e272609165c9.png)

**Comment by nocalla** [comment]
Okay, great - I can work with that. So it looks like the format is as follows:

```
Source Filename Pattern = [0-9]{3}-[0-9]{6}-[0-9]{2}_[0-9]{3}
Source Filename Extension = .txt
Use Regex for Filename = True
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Memo,Inflow
```

Can you confirm if those Input Column names look right to you? Also, if you right click the text file to open it in Notepad, are the columns separated by the `,` symbol or does it use something else?

**Comment by ricardopolo** [comment]
I dont think it uses `,` i think it uses tab.  I uploaded it.
[049-594671-16_456.txt](https://github.com/bank2ynab/bank2ynab/files/5922214/049-594671-16_456.txt)


The format is:
Date,Document,Office,Memo,Reference,Value

**Comment by nocalla** [comment]
Last question, hopefully - from Document, Office, and Memo; what do you use as Payee and Memo in Ynab?

**Comment by ricardopolo** [comment]
None of them is the Payee.
Document is a number I don't use.
Office is the name of the bank office.
Description is the memo.
Reference is a number I don't use.
