### ISSUE TITLE
Support for Mint [Other Budgeting Software]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#108]
Sourced from [tehmikey/YNABFileConverter
](https://github.com/tehmikey/YNABFileConverter/blob/master/YNAB.py)

`MINT_HEADER=['Date','Payee','Memo','Amount','TransactionType','Category','AccountName','Labels','Notes']`

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

From Issue #21 master list

**Comment by nocalla** [comment]
This should be an easy one.

**Comment by torbengb** [comment]
Only missing spec is the filename itself, but [Mint's website declares it](https://community.intuit.com/articles/1763070-import-transactions-from-mint) to be "transactions.csv" so that's what I used.
