### ISSUE TITLE
Support for Easybank [AT]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#112]
Name of Bank: Easybank
Country: Austria [AT]

Sourced from [jbogard/EasyBankToYnab](https://github.com/jbogard/EasyBankToYnab)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master Issue #21

**Comment by torbengb** [comment]
Solved, at least for credit card. Hope that's enough? Otherwise please open a new ticket!
