### ISSUE TITLE
Support for OTP [HU]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#136]
Name of Bank: OTP
Country: Hungary [HU]

Source: [abesto/otp2ynab](https://github.com/abesto/otp2ynab)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by abesto** [comment]
Hi! Dude from `abesto/otp2ynab` here.

OTP supports both CSV and XML exports. The CSV format is ... weird. I had little success trying to consolidate their three to five memo fields, for example. Instead of that I've been using the XML export, which is _almost_ a standard.

I “wrote” (copy-pasted and hacked until it worked) https://github.com/abesto/ofxstatement-otp that takes their exported XML, and converts it to an OFX; that's how my current solution works. I understand `bank2ynab` is all about CSV, which makes things a bit harder; I honestly have no wish to revisit the CSV exported OTP format, it was a traumatic event. I guess XML -> `ofxstatement` -> OFX -> (some simple script) -> CSV -> `bank2ynab` would be technically possible, but not really sane.

What are your thoughts?

**Comment by abesto** [comment]
I notice the beginnings of a plugin system, maybe that'd be a way to add in the XML -> internal format step? Though I expect we'd still want to pull in the existing code as a dependency.

**Comment by nocalla** [comment]
Hey @abesto, thanks for getting back to us. 

Do you have a sample file that we could use to get an idea of what formatting we have to deal with? And I hate to bring up old trauma, but can we see the CSV format too? There might be something we have dealt with in other weird formats or something we haven't thought of incorporating into the parser.

The plugin system is a little more advanced in the pull request active in #169, adding a preprocess step that would be a useful point for XML conversion - allowing for going from XML to CSV using a regex maybe and then processing as normal from there. That pull request should be merged over the weekend, I just want to do some final testing.

**Comment by abesto** [comment]
Sure, I'll get you some (anonymized) samples, ideally within a few days.

As for using regular expressions to process XML / HTML, at the risk of putting my nose where it's not welcome: there's an obligatory StackOverflow post on that: https://stackoverflow.com/a/1732454. In short: you can save a lot of trouble by using a “proper” parser, since regular expressions are not “mathematically” strong enough to properly parse XML / HTML. This is where integrations with existing strong parsers come in, a 'la https://github.com/kedder/ofxstatement.

**Comment by nocalla** [comment]
As a baby programmer, I didn't realise there were options were regex was
inherently bad. I'd better avoid summoning the elder gods. I'll look into
parsers, but am trying to avoid non-standard libraries where possible.

**Comment by nocalla** [comment]
Then again, I'm not trying to *parse* the HTML, just to strip out all the
HTML elements.

**Comment by abesto** [comment]
Hwell. I spent the past 15 minutes trying to scrub personal data from an OTP XML export about two days of transactions, and managed to create... an XML file that's not valid. Instead, I'll refer you to https://github.com/abesto/ofxstatement-otp/blob/master/src/ofxstatement/plugins/otp.py that implements a parser for the XML export format for OTP (which is _almost_ exactly CAMT.053 (ISO-20022))

As for CSV:

```
"account-id-goes-here";T;-4;HUF;20180115;20180115;[balance after transaction];;;"SPAR [redacted]";;"2018.01.13 6247129463";VĂSĂRLĂS KĂRTYĂVAL;;
"account-id-goes-here";T;-9;HUF;20180115;20180115;[balance after transaction];;;"Mazsa Team Kft             PPASS";;"2018.01.14 6247129463";VĂSĂRLĂS KĂRTYĂVAL;;
"account-id-goes-here";J;2;HUF;20180116;20180116;[balance after transaction];another-account-id;"personal name redacted";;;;NAPKĂ–ZBENI ĂTUTALĂS;;
"account-id-goes-here";T;-2;HUF;20180116;20180116;[balance after transaction];;;"SLOW FOODIEZ               PPASS";;"2018.01.13 [number redacted]";VĂSĂRLĂS KĂRTYĂVAL;;
"account-id-goes-here";T;-5;HUF;20180116;20180116;[balance after transaction];;;;;"2018.01.15 [number redacted]";KP.FELVĂ‰T/-BEFIZ. DĂŤJA;;
"account-id-goes-here";T;-1;HUF;20180116;20180116;[balance after transaction];;;"Budapest,[redacted]";;"2018.01.15 [number redacted]";KĂ‰SZPĂ‰NZFELVĂ‰T ATM-BĹL;;
"account-id-goes-here";T;-2;HUF;20180116;20180116;[balance after transaction];;;"ENHU[redacted]";;"2018.01.15 [number redacted]";KĂ‰SZPĂ‰NZFELVĂ‰T ATM-BĹL;;
"account-id-goes-here";T;-7;HUF;20180117;20180117;[balance after transaction];;;"OTPdirekt internet";"another-account-id";"2018.01.16 [number redacted]";BANKKĂRTYĂK KĂ–ZĂ–TTI UTALĂS;;
```
Some general notes:

 * column 2 (`T`/`J`) most likely stands for “*j*óváírás" (monies added to account) or "*t*erhelés" (monies left account)
 * one of the dates is probably when the transaction was made, the other probably when it was booked
 * the column with "SPAR" in the first line is the name of the other party in the transaction
 * the column with "VĂSĂRLĂS KĂRTYĂVAL" in the first row is (one of) the memo field(s)

The transactions, in order:

 * Purchased stuff with a credit card, vendor name is "SPAR [redacted]", for 4 HUF
 * Spent another 9 HUF at "Mazsa Team Kft" with PPAS ("PPAS" probably stands for paypass, the Hungarian fantasy name for contactless)
 * "personal name redacted" transferred 2 HUF from "another-account-id"
 * Spent another 2 HUF at SLOW FOODIEZ using a credit/debit card
 * Withdrew 1 HUF from an ATM
 * 2 HUF was charged for the previous withdrawal
 * Sent 7 HUF from one credit card in the account to another card in the same account

**Comment by nocalla** [comment]
Hey @abesto, sorry to resurrect an old issue for you, but what's the format of the csv export's filename?

**Comment by nocalla** [comment]
Proposed bank configuration, missing source filename details, but otherwise straightforward.

```
[HU OTP]
Source Filename Pattern = example_transaction_export_filename
Source CSV Delimiter = ;
Source Has Column Headers = False
Input Columns = skip,skip,Inflow,Date,skip,skip,skip,skip,Payee,skip,skip,Memo,Memo,skip
Date Format = %Y%m%d
```

**Comment by abesto** [comment]
Ohai! Apologies for the delay. Happy to see progress here. The CSV export filename is, boringly, `export.csv`.

**Comment by nocalla** [comment]
Great, thanks.
