### ISSUE TITLE
Support for Starmoney [Banking Software]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#142]
Name of Bank: Starmoney [Banking Software]

Source: [fpoppinga/ynab-converter](https://github.com/fpoppinga/ynab-converter)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Issue #21

**Comment by torbengb** [comment]
Updated format based on way too much .js reading:

```
[Starmoney]
# source: Issue #142
Source CSV Delimiter = ;
```

... that's really the only thing I can deduce from the source, and there's no sample data.
@nocalla I think we should abandon this issue, what do you think? Label=wontfix?
