### ISSUE TITLE
OFX next to / instead of CSV?

### ISSUE THREAD

**Issue by abesto** [bank2ynab/bank2ynab#170]
YNAB recommends using OFX whenever possible, citing CSV as a “last resort” (https://www.youneedabudget.com/fbi/). Bringing OFX into the flow as a supported input / output format would

 * make the output compatible with any number of other budgeting solutions, not just YNAB
 * make the input trivial for any well-behaved banks that provide OFX exports
 * allow reuse of the already existing vast collection of importers over at https://github.com/kedder/ofxstatement, while YNAB-specific features could still be added here

**Comment by nocalla** [comment]
Yep, probably makes sense to include the option. Have you a resource that outlines requirements for OFX that you can link here?

**Comment by abesto** [comment]
I can't seem to find any actual specification for exactly what OFX fields are used by YNAB. I'll include a “good” OFX file for the sample data I'll collect for #136.

**Comment by torbengb** [comment]
I like the idea of OFX simply because it's a standard and because YNAB seems to like it. *However...* I like CSV even more simply because it's a standard and because it is so straightforward to work with, even for humans. 

I've never actually seen an OFX file, so if that is as easily readable as CSV then I'm all for it. (Good thing we don't have "CSV" in our package name :-P )

**Comment by abesto** [comment]
CSV is not a standard though. https://chriswarrick.com/blog/2017/04/07/csv-is-not-a-standard/ goes into detail. https://en.wikipedia.org/wiki/Comma-separated_values also explains:

> The CSV file format is not standardized. The basic idea of separating fields with a comma is clear, but that idea gets complicated when the field data may also contain commas or even embedded line-breaks. CSV implementations may not handle such field data, or they may use quotation marks to surround the field. Quotation does not solve everything: some fields may need embedded quotation marks, so a CSV implementation may include escape characters or escape sequences.

That's why most proper CSV packages allow you to define your "variant" (and provide a number of widely used defaults, like the Excel CSV format).

I'm not arguing for or against CSV, it's for you to know how this should influences your design decisions, but you should have all the info :)

**Comment by nocalla** [comment]
We should probably make inclusion of this option part of 1.0.

**Comment by torbengb** [comment]
I disagree - OFX is clearly out of scope for v1.0, as it was never part of our original idea. By all means, let's build it, but I don't see it as a blocker for release 1.0.

**Comment by nocalla** [comment]
Yeah, that's fair. 1.1 maybe.

**Comment by torbengb** [comment]
Speaking of, I'm confused my the "projects" area of GitHub, especially versus the milestones. Are we going to use either of them, do you think?

**Comment by nocalla** [comment]
We probably should use them as a shorter to-do list function so we can do
"sprints" or at least more focused application of efforts.

**Comment by abesto** [comment]
I can't seem to find an easy-to-consume documentation of OFX. The official spec is available at http://www.ofx.net/. There are already some Python libraries / tools that deal with OFX:

 * https://github.com/captin411/ofxclient downloads information from banks
 * https://github.com/jseutter/ofxparse parses OFX files into Python objects
 * https://github.com/reubano/csv2ofx converts CSV files into OFX

As promised, here's a minimal OFX file importable into YNAB:

```xml
<OFX>
	<BANKMSGSRSV1>
		<STMTTRNRS>
			<STMTRS>
				<BANKTRANLIST>
					<STMTTRN>
						<TRNTYPE>DEBIT</TRNTYPE>
						<DTPOSTED>20180201160000</DTPOSTED>
						<TRNAMT>-79.97</TRNAMT>
						<NAME>Some bank</NAME>
						<MEMO>Test memo 1</MEMO>
					</STMTTRN>
					<STMTTRN>
						<TRNTYPE>DEBIT</TRNTYPE>
						<DTPOSTED>20180202160000</TDPOSTED>
						<TRNAMT>-42.96</TRNAMNT>
						<NAME>Some dude</NAME>
						<MEMO>Test memo 3</MEMO>
					</STMTTRN>
					<STMTTRN>
						<TRNTYPE>DEBIT</TRNTYPE>
						<DTPOSTED>20180202160000</DTPOSTED>
						<TRNAMT>-34.96</TRNAMNT>
						<NAME>Some ISP</NAME>
					</STMTTRN> 
				</BANKTRANLIST>
			</STMTRS>
		</STMTRNRS>
	</BANKMSGSRSV1>
</OFX>
```

**Comment by nocalla** [comment]
Are the indentations required?

**Comment by torbengb** [comment]
I'm not familiar with OFX but very much with XML and based on that I'm sure all formatting whitespace can be ignored.

**Comment by nocalla** [comment]
In that case, this looks trivial to code.

**Comment by abesto** [comment]
Quick update: looks like `ofxstatement` does CSV imports too, this was news to me. `ofxstatement-otp` has just received a PR that implements parsing of (some of the) CSV format(s) exported by OTP: https://github.com/abesto/ofxstatement-otp/pull/1/files

**Comment by nocalla** [comment]
Since we're sending the transactions directly into the YNAB API now, I don't see the need for providing additional output formats. Closing.
