### ISSUE TITLE
`pip install bank2ynab`?

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#176]
I noticed that [pynYNAB](https://github.com/rienafairefr/pynYNAB/blob/master/README.rst) offer a brilliantly simple installation: 
`$ pip install pynYNAB`; and [Anders' converter](https://github.com/andsens/ynab-csv-converter#installation) does it even simpler: 
`pip3 install https://github.com/andsens/ynab-csv-converter/archive/master.tar.gz`

How did they do this, and what would it take to offer `bank2ynab` in the same fashion? 

Does it require a snapshot of `bank2ynab` to be placed into a central repository? How can that be kept up to date automatically?

**Comment by torbengb** [comment]
The blog post [How to submit a package to PyPI](http://peterdowns.com/posts/first-time-with-pypi.html) gives a nice summary of "how".

**Comment by nocalla** [comment]
That's pretty cool. Seems straightforward enough to do.

**Comment by torbengb** [comment]
Yes, that blog post isn't half bad. Still, it's a bit of a rabbit hole:

1. It seems we should move our files into a subdirectory though, so that there is a "root" for the meta files described. I don't really like the idea of having a path like `bank2ynab/bank2ynab` but what else would be a good name for the subdirectory? 

1. We should probably open up a new branch to do this, so we don't mess up our main develop branch -- and we probably shouldn't do that right now while Travis isn't happy?

1. PyPI sort-of forces us to introduce actual version numbers which we're sort-of trying to build up anyway. To do that, GitHub provides [releases](https://github.com/torbengb/bank2ynab/releases) and [tags](https://github.com/torbengb/bank2ynab/tags) that we haven't started using yet. New territory for me. 

1. So I guess we should be making a [new release](https://github.com/torbengb/bank2ynab/releases/new) `1.0` based on the `master` branch after we've merged `develop` into it, right? That page also wants a "Release title" -- is that just `1.0` again or should it be something else?

1. The first release we're aiming for right now would then be 1.0.0, according to the [semantic versioning](https://semver.org/) which GitHub suggests on the new-release page. If we start doing that kind of versioning, then we're committing ourselves to keep making new tags and releases as we go, instead of simply merging to `master` and be done with it. OTOH, we can keep on merging to `develop` and only make a new actual release once every blue moon. I wonder what a sensible release criterion would be.

It just means adding a bunch of meta overhead and I am not sure what the benefit of that effort really is. Am I understanding this right? Are you okay with that prospect of overhead? I mean, I am all for doing things "right" and all, I just don't want to commit this project to more work than we really have to, or want to.

(I know you're reading these comments by email. I used some markup for the list and hyperlinks and I have no idea whether that survived the trip to your inbox. If the above looks oddly formatted to you, try at GitHub directly.)

**Comment by torbengb** [comment]
After the merge to `master`, I've taken the liberty to tag and release it as `v1.0.0` with [a short blurb](https://github.com/torbengb/bank2ynab/releases/tag/v1.0.0) as release notes.

**Comment by torbengb** [comment]
TO DO:
- [ ] Convert README.md to README.srt #191
- [ ] modify `setup.py` line 84: classifiers="..."
- [ ] do we have to ditch the `v` prefix of the version string? ([source](https://packaging.python.org/tutorials/distributing-packages/#choosing-a-versioning-scheme))

**Comment by torbengb** [comment]
I've implemented (most of?) the required work in the branch `feature-176-pypi-installer` and updated the wiki page accordingly with a detailed guide. Will test it myself, perhaps tonight.

**Comment by torbengb** [comment]
Check out [these "How" steps in the wiki](https://github.com/torbengb/bank2ynab/wiki/PublishRelease#how):
5. OK: I have uploaded several sample versions to the PyPI test system, 
7. OK: ... and I am able to install them on my computer!
8. FAIL: ... but the `bank2ynab` script doesn't work when installed: 

> ImportError: No module named bank2ynab

So I'm still working on it, and haven't uploaded anything to the production PyPI yet!!

**Comment by torbengb** [comment]
Oh, and "yes" we have to get rid of the "v" prefix in the version numbers, otherwise the PyPI upload fails.

**Comment by torbengb** [comment]
I'll need to do a much simpler test in order to get the basic packaging procedure going. 

To do @torbengb: 

- [ ] branch off from `feature-176-pypi-installer` into a dummy branch,
- [ ] prune the branch to an absolute minimum that can be packaged,
- [ ] get the packaging working with that dummy,
- [ ] merge the "best practise" from the dummy branch back into `feature-176-pypi-installer`.

**Comment by nocalla** [comment]
Here's something interesting about using Travis for this. https://docs.travis-ci.com/user/deployment/pypi/

**Comment by nocalla** [comment]
*cough cough* Github Actions *cough cough* #308

**Comment by nocalla** [comment]
Tackling this from a general packaging and distribution perspective over on #349.
