### ISSUE TITLE
Convert README.md to README.srt

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#191]
This conversion might be necessary according to 
https://github.com/pypa/sampleproject#a-sample-python-project
but I'd rather avoid the effort if the .md format works just as well, so that needs to be tested.

Note that I created a milestone for this issue in order to tie it together with #176. That's a test to see if it makes sense to do so.

**Comment by nocalla** [comment]
The sample's README is a .md file, so looks like it's not required?

**Comment by nocalla** [comment]
According to https://packaging.python.org/guides/making-a-pypi-friendly-readme/, .MD files are just fine.
