### ISSUE TITLE
Use logging instead of print()

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#214]
**Other feature request**

**Is your feature request related to a problem? Please describe.**
It seems to not be best practice to use print(). A better option is to use logging. This will also allow us to improve debugging if needs be, as well as providing scope for higher priority warnings etc.

**Describe the solution you'd like**
Let's implement logging instead of our print calls.

**Describe alternatives you've considered**
We could keep the print as-is, but it's annoying to work around and it would be nice to have the debugging features logging provides.

**Additional context**
Some references about logging:
- [StackOverflow Question](https://stackoverflow.com/questions/6918493/in-python-why-use-logging-instead-of-print)
- [5 minute quickstart guide to python logging module](https://inventwithpython.com/blog/2012/04/06/stop-using-print-for-debugging-a-5-minute-quickstart-guide-to-pythons-logging-module/)
- [Gist with practical implemenations of logging](https://gist.github.com/neuroticnerd/7c60d61c8d9d9716f50d)

**Comment by nocalla** [comment]
I've merged this into develop with #215 as it didn't break anything. I'd like help improving how the logging works though, particularly allowing the test files to not use the INFO lines for a cleaner test output. @toyg - do you have any feedback here?

**Comment by toyg** [comment]
Step 1: the logging level must be set in a config file, not in source. The simplest way to achieve this is to have a parameter that can have a value ("INFO"), then in code something like: 
```
basicConfig(level=getattr(logging,your_param)
```
(you might want to have a check before: `if your_param not in ['INFO','DEBUG'...]: your_param='ERROR'`) 

Step 2: if you want to do something more complicated/precise, have a look at `dictConfig()`. 

Step 3: you can have a simple environment variable (say DEBUG=1) and depending on that value, switch between basicConfig and dictConfig, so you can e.g. pass a complicated config for debug purposes, and a simple one for production default.

I'm not a test guru, I'm sure there are many other ways to skin this particular cat, but the ideas above are the simplest strategies and rely on simple stdlib modules.

**Comment by nocalla** [comment]
So where this stands now is that we need to add a switch for the different logging levels and assign priorities to each message in the code.

**Comment by nocalla** [comment]
I'm going to mark this as done and create a separate issue for creating filters etc.
