### ISSUE TITLE
Test Support for DK banks with online solution produced by "Bankernes EDB Central" (BEC)

### ISSUE THREAD

**Issue by duch11** [bank2ynab/bank2ynab#219]
Hi while adding support for DK Arbejdernes Landsbank, I found out that many Danish banks uses the same online banking solution. It's produced by "Bankernes EDB Central" and therefore my update might have ended up adding many more Danish banks to the "Supported" List. 

Support added and verified for: 
- **Arbejdernes Landsbank DK** Verified
- **Merkur Andelskasse DK** Verified
- **Handelsbanken DK** Verified
- **Sparekassen Thy** Verified

The following list of banks, are potentially supported due to their membership with BEC, but I'm unsure if they all use same default settings etc in their export tool.

So, I need customers of these banks to test out if they work with my added config for BEC.

- Nykredit Bank
- Spar Nord
- VestjyskBANK
- Danske Andelskassers Bank
- Den Jyske Sparekasse
- GrønlandsBANKEN
- Fynske Bank
- Lollands Bank
- Salling Bank
- Lægernes Bank
- Totalbanken
- Møns Bank
- PenSam Bank
- Hvidbjerg Bank
- Frørup Andelskasse
- Andelskassen Fælleskassen
- Faster Andelskasse
- Frøslev-Mollerup Sparekasse
- Københavns Andelskasse

### Test with the following settings in the export tool:
**Date:** "whatever you need"
**Exportformat:** Default (CSV)
**Checkboxes:** "All unchecked"
**Filename:** Blank

How it should look:
![billede](https://user-images.githubusercontent.com/17031368/43408715-5192657a-9422-11e8-80fc-827592018758.png)

**Comment by duch11** [comment]
**Handelsbanken DK** added in pull request #220

**Comment by simzdk** [comment]
Mangler understøttelse for Sparekassen Thy: 
https://pastebin.com/cXMMkeHw

**Comment by duch11** [comment]
Will be looking into it :)

**Comment by duch11** [comment]
Hvad hed filen da du downloadede den? Det skal være hvad banken selv kalder filen.

**Comment by nocalla** [comment]
I **think** it will include the header line in the final file, but I don't think it will crash or cause problems other than that.

**Comment by duch11** [comment]
> 
> 
> Hej drenge,
> there's a checkbox `[ ] include column headings` that the user might check, so it would be prudent to be able to handle the CSV with and without a header row.
> It might be easy but this needs testing: if we specify "no header row" in the format, but there is one in the file, will our tool simply ignore that line and correctly output the rest?

Good question, it would increase ease of use for sure..

**Comment by duch11** [comment]
> 
> 
> Mangler understøttelse for Sparekassen Thy:
> https://pastebin.com/cXMMkeHw

Just fixed the issue with Thy Handelsbanken.
Still need the correct filename tho.. temp filename: "thyposteringer"

**Comment by nocalla** [comment]
Spareassen Thy works and I've merged it into Develop. The issue was with the delimiter still being a comma instead of a semi-colon.

**Comment by duch11** [comment]
Oh.. Ok 👍 
What a journey :)

**Comment by torbengb** [comment]
Do all of these have the same default file name?

I'm asking because I am trying to count how many banks we support so far, and this format counts as one but covers many. 

I think we should list all the ones you've successfully tested in the README.md and I'm not sure how to keep track. Not sure how our issue #239 would interfere or support this.

**Comment by duch11** [comment]
It seems to vary a great deal unfortunatly, so I'm not sure whether to just close this and let people be happily surprised when they try their unsupport bank out and it works..

**Comment by nocalla** [comment]
I'm just going to have #239 read the section headers, add them to the list, and sort the list. Maybe we can call the section heading something generic that applies to these banks? Otherwise the section header will be looooooong!

**Comment by nocalla** [comment]
Well if the filename is different they require different configurations. So that would solve the Section Name issue.

**Comment by 3dmikkelsen** [comment]
I've tried to add Jutlander bank, but only gets a fixed_ file containing headers. Any good ideas? 
PS. no coding experience what so ever!

**Comment by nocalla** [comment]
@3dmikkelsen - is that one of the banks using the system described above? If not, can you make a new issue for it please?

**Comment by jtpedersen** [comment]
I had a bit of a fight with encoding issues on the BEC export, only to find out that it was due to me exporting columns that the csv parser choked on. I wonder if if would be possible to specify / document the needed export settings in the conf file or somewhere else where it would be noticed. as opposed to finding this issue ;)

**Comment by sloev** [comment]
I have created a script to extract transactions from these kind of systems using headless scraping. Check it here:
https://github.com/sloev/nemid_bank_transcripts
