### ISSUE TITLE
Travis upgrade to Github Checks API

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#224]
Travis has been updated to use the new Github Checks protocol instead of the old API, so he's not working properly. Only @torbengb has the power to fix this! Instructions are here: [https://docs.travis-ci.com/user/open-source-on-travis-ci-com](https://docs.travis-ci.com/user/open-source-on-travis-ci-com)!

**Comment by nocalla** [comment]
So apparently the open source project migration has been pushed back but we can manually request a migration. 

"Repositories may also be migrated without their build history or build settings (including environment variables) immediately. Please contact support support@travis-ci.com and include “Repository Migration” somewhere in the subject line, and the name of the repository in your email."

**Comment by nocalla** [comment]
Incidentally, it might be worth making an "organisation" for this project so you don't get landed with all the administration for external tools.

**Comment by torbengb** [comment]
> might be worth making an "organisation" for this project

Oh absolutely! I sometimes feel bad about having this cool project under my name while so many other people make awesome contributions to it. How, though? I found [this blog post](https://blog.github.com/2010-06-29-introducing-organizations/) and also [this page for my own user](https://github.com/settings/organizations) where I can convert my entire personal user account into an organisational account - but I am still looking for how to move _just this repository_ to a (new or existing?) organisation. 

Of course we can create an organisation and fork my repo to that, but we'd only get the code and not all of the configuration. Do we get the wiki? Do we get the (unresolved) tickets? I don't think so.

**Comment by nocalla** [comment]
I've activated the organisation on Travis, but he's not up and running just yet. Will see what happens.

**Comment by nocalla** [comment]
I've sent an email to the Travis-CI support to get our friend back on his feet.

**Comment by nocalla** [comment]
Fixed! Travis lives!
