### ISSUE TITLE
Move this repository from individual user `torbengb` to a new organisational user account `bank2ynab`

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#225]
[@nocalla suggested](https://github.com/torbengb/bank2ynab/issues/224#issuecomment-429286892) that _it might be worth making an "organisation" for this project._ 

That's a good idea! I sometimes feel bad about having this cool project under my name while so many other people make awesome contributions to it. 

**How, though?** 

I found [this blog post](https://blog.github.com/2010-06-29-introducing-organizations/) and also [this page for my own user](https://github.com/settings/organizations) where I can convert my entire personal user account into an organisational account - but I am still looking for how to move _just this repository_ to a (new or existing?) organisation. 

Of course we can create an organisation and fork my repo to that, but we'd only get the code and not all of the configuration. Do we get the wiki? Do we get the (unresolved) tickets? I don't think so.

**Comment by nocalla** [comment]
As far as I can see, you can make a new organisation and actually *move*
this report into that. Maybe make the organisation first and create roles.

**Comment by torbengb** [comment]
- create organisation: check!
- create roles: check! I've invited you.
- move this repo there: how?

**Comment by torbengb** [comment]
[User Documentation: Transferring a repository owned by your personal account](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)

**Comment by torbengb** [comment]
It seems from the description that when the project is transferred, the present URL `.../torbengb/bank2ynab/` will automatically redirect to the new URL `.../bank2ynab/bank2ynab/` instead - as long as I don't create a new project also named `.../torbengb/bank2ynab/`!

> If you create a new repository under your account with the same name as the transferred repository, existing redirects to the transferred repository will break. Instead, use a different name for the new repository. - [source](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)

I'm doing the transfer now, and keeping my fingers crossed that nothing breaks!!

**Comment by nocalla** [comment]
Seems to have worked!

**Comment by nocalla** [comment]
Migration seems all fine. Closing #225.
