### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by filoor** [bank2ynab/bank2ynab#242]
hi,

I have downloaded the zip i have also extract he zip.
I have edit the bank2ynab.conf 
Change the Source Path only 
when i run python bank2ynab.py
It will say Done! 0 files processed.

It wont see my rabobank csv.

**Comment by torbengb** [comment]
Hello Filoor!
Thanks for trying `bank2ynab`! I'm sorry that you're having trouble.

What is the EXACT name of the file you have downloaded from your banking website? 

The configuration expects Rabobank files to be named either "transactions.txt" (2017 and older) or something like "CSV_A_20180414_112204.csv" (2018 format). So my first suspicion is that perhaps the name of your file does not match either of these two. 

If that is not the case, could you please double-check that the file path specified in the configuration really does match the path to your downloaded file?

Regards,
Ben

**Comment by torbengb** [comment]
Hi Filoor! 
Thanks for trying `bank2ynab`! I'm sorry you're having trouble. Let me try to help.

What is the EXACT name of your file?

The configuration for Rabobank expects the filename to be either "transactions.txt" (2017 format) or "CSV_A_20180414_112204.csv" (2018 format). Does your file name match either of these two?

If that does not help you, please double-check that the file path in your configuration really does point to the path where your file is. If that still doesn't help you, then please reply.

If this solves your issue, please come back and mark this issue as closed. Thank you!

Regards,
Ben

**Comment by filoor** [comment]
Hi,

Thank you for your quick replay
This is my file path "C:\Users\TARIK.FIL\Desktop\firefly\bank2ynab-master\bank2ynab-master\CSV_A_20181103_154701.csv"
and this is what i have in my config.

Source Path = C:\Users\TARIK.FIL\Desktop\firefly\bank2ynab-master\bank2ynab-master

**Comment by torbengb** [comment]
> \bank2ynab-master

_Aha!_ :-) I think you're looking at the initial release version which only included the 2017 Rabobank format. Much has been implemented since then, and we're close to releasing the v1.1.0 update, but it's not out yet. 

Please download the development copy from here: https://github.com/bank2ynab/bank2ynab/archive/develop.zip 

Unzip that file, then please specify your CSV source path in `user_configuration.conf`.

Hope this helps!
Regards from Austria,
-Ben

**Comment by filoor** [comment]
Thanks that it
