### ISSUE TITLE
IE Bank of Ireland, current

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#244]
- Full name of the bank: Bank of Ireland
- Country (2-character country code): IE
- Any special requirements: Current account

This is survey response #37.

```
Source Filename Pattern = !unknown!
Source Filename Extension = .csv
Use Regex for Filename = False
Input Columns = Date,Payee,Outflow,Inflow,skip
Date Format = 
# (see http://strftime.org/ for date format strings)
```

**Comment by nocalla** [comment]
This is my bank and is already in the config.

**Comment by torbengb** [comment]
Oops, haha - so we can close this issue! I am confused, why was it added to
the survey?

**Comment by nocalla** [comment]
Someone else may have added it.

**Comment by nocalla** [comment]
For reference, here's what's in the config. 
```
[IE Bank of Ireland]
# TransactionExport.csv
Source Filename Pattern = TransactionExport
Input Columns = Date,Payee,Outflow,Inflow,skip
```
