### ISSUE TITLE
Properly test Python 2.7 in Travis

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#252]
**Is your feature request related to a problem? Please describe.**
Python 2.7 was not being properly tested in Travis. The test suite doesn't register the different Python version and just results in a load of errors due to it being processed like a Python 3 file.

**Describe the solution you'd like**
More robust checking of Python version is needed in the test suite.

**Describe alternatives you've considered**
We could drop Python 2 support!

**Comment by torbengb** [comment]
Does "wontfix" mean we aren't testing 2.7, or we are no longer supporting 2.7? If the former then fine by me; if the latter then I'd like to update the docs to match it.
(Trying to catch up the summer's email backlog)

**Comment by nocalla** [comment]
As per #267, as Python 2 support is ending we should phase out support for it. Maybe mark one version as the Python 2 cutoff. This is marked wontfix because I have no intention of working out how to make Python 2 register with Travis properly.

**Comment by torbengb** [comment]
Fine - so this means Travis just doesn't test it anymore. 

I wish we had some sort of user stats that could tell us whether 2.7 is even required by anyone. (googling...) Oookay, Py3 is already 11 years old!!?! Now it almost feels embarrassing that we ever bothered about it :-)

I will go through the docs and remove any mention of 2.x.
