### ISSUE TITLE
Direct control over Category field during import?

### ISSUE THREAD

**Issue by ressy** [bank2ynab/bank2ynab#264]
I'm finally trying to get on board the nYNAB train, and had the unpleasant surprise that my own converter script's handywork on the Category column is no longer respected on import.  [The YNAB forum has a post](https://support.youneedabudget.com/t/x1bw4k/how-to-import-categories-from-csv) asking the same, but it sounds like this is one of those things they mysteriously left out of the new version.  I've been meaning to take the time to try to add my converters in your project here so maybe this'll force my hand!

More context:

I've been using that feature for years to automatically create a Category column based on different conditions in CSV exports from [Shopify](https://www.shopify.com/).  I know this is an edge case for most YNAB users, but for a small business, it adds one special piece to make YNAB feasible for first-stop cash flow tracking and budgeting across accounts.

So now I'm trying to figure out if switching to the API instead of file import would give me that control, and if that's feasible.  I know things here are largely file import-based but I see some recent discussion on the API and categorization including in #192:

> How do you feel about importing categories into YNAB, if the categories were somehow known? Would that be 100% useful or how often would that not be useful to you?

**100% useful!** :)

> It would be nice if the CSV already contained the correct category

It's a shame that this completely reasonable behavior existing in YNAB 4 no longer works in new YNAB.

Worst-case workaround could be to programmatically set more specific payees based on intended category and let YNAB remember the mapping between the two, I guess.  Or maybe something could be whipped up via http://toolkitforynab.com/ to enforce a given Category column in a CSV, if enough of the import logic is handled client-side.  No idea if it is, but that browser extension saved me a few times already and it's only been two days so I'm hopeful ;)

Any ideas?  Is this too niche a use case to matter and I should just use the payee workaround, or would others want this sort of  thing too?

**Comment by nocalla** [comment]
Hi there. Good question. It was my understanding that if the category already existed in YNAB, it would be used with the transaction. Obviously that hasn't been your experience though! 

The good news is that this seems like it would be reasonably trivial to accomplish with our current setup in the (in-progress!) YNAB API branch ( discussed over on #192 and #262). 

If Category is specified in your config for an import file, it'll get passed to the API uploader after cleanup. That doesn't do anything with Category right now, as we're still working on that uploader, but it's something I'll make available when tinkering with that. 

Personally, I'd be inclined to use the Payee tools, which have quite robust renaming and categorisation rules, e.g. you could have a rule that renamed anything with "WHOLESALER 7" contained in the payee name and auto-categorise that. Obviously, I'm not familiar with your workflow so that might make no sense.

**Comment by ressy** [comment]
Thanks for the quick reply.  Thinking on it more, I think you're right, if I just set up a few more specific Payee entries I'll get what I want with minimal hassle.  It's not really a big deal to have a group of related payees named using a common prefix or something.  Are we able to batch-update payees for a set of transactions in the new interface, do you know?  That'd be my last missing piece to make it all consistent both before and after.

> It was my understanding that if the category already existed in YNAB, it would be used with the transaction. Obviously that hasn't been your experience though!

Yeah, it surprised me that this hadn't come up earlier, maybe because most people keep a 1-to-1 relationship for Payee-to-Category so it still does the right thing most of the time by matching the last-seen category per payee?  I'll still nag the YNAB devs since it bothers me to not have direct control in our CSV imports, and if they don't implement it I think it'd be a great feature to have control over here, but for my purpose the pragmatic approach is probably just to work with the current behavior and use more payees.

**Comment by nocalla** [comment]
I'll add category upload to the API integration regardless, so if you do end up needing it, just add Category to your own config file in the appropriate spot in Input Columns.

**Comment by ressy** [comment]
That sounds perfect!  Thanks so much.

On a side note I'm working on a branch adding support for the formats I need for this, starting with plugins but heading toward just plain config file entries if I can manage it.  This layout (config file and plugins via subclasses) is really clear and flexible so thanks for that too.  I'll drop in a pull request when I have something worth merging.

**Comment by torbengb** [comment]
Every new format added to 'bank2ynab' makes it a better solution for more people. We'll be looking forward to your contribution - thank you for participating!
