### ISSUE TITLE
End support for Python 2

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#267]
**Is your feature request related to a problem? Please describe.**
Python 2 official support is ending at the end of 2019. We should do the same. 

**Describe the solution you'd like**
We should look at finalising the version for Python 2.7 and cutting out the workarounds for Python 2 for future development. 

**Describe alternatives you've considered**
Leave Python 2 support in place. This leads to more complex maintenance and addition of new features becomes more cumbersome. I've run into difficulties with the new API development as a result of the Python 2 workarounds we have in place. 

**Additional context**
https://pythonclock.org

**Comment by torbengb** [comment]
I've now updated the docs (mostly the readme) to say only Py3 is supported.

**Comment by nocalla** [comment]
Nice. Next step is to remove all the Python 2 compatibility hacks...may take some time!

**Comment by torbengb** [comment]
Well, we can claim that we have right now ended official support for py2. As long as those compat hacks aren't too much of a bother, they can stay in the code. (If it works, don't fix it...) 

When some piece of py2 code needs to be worked on, I'd say that's the time to py3'ify it. I know we won't do it sooner "just for fun" anyway.

**Comment by nocalla** [comment]
An update- Python 2 officially retired now, so will be working to strip out references to it.
