### ISSUE TITLE
plugin-RaiffeisenRCM returns error 400

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#269]
**Describe the bug**
1. I have created the branch `plugin-RaiffeisenRCM` which contains a plugin to read the Raiffeisen-proprietary file format `RCM`. 
1. This plugin includes currency conversion from legacy ATS to EUR using a fixed currency conversion rate. It is correct to use a fixed currency conversion rate; this is part of the RCM format definition.
1. Bank format + plugin + test data is provided in the branch.

**What did you EXPECT to happen?**
Successful upload and import into YNAB.

**What ACTUALLY happened?**
1. When executed, the program correctly reads and parses the input file. 
1. It also correctly generates the output file -- except that **it does not have the YNAB header row**.
1. The program then tries to upload this file to the YNAB API but we get an error:
```
INFO: Uploading transactions to YNAB...
INFO: Starting new HTTPS connection (1): api.youneedabudget.com
ERROR: 400 - Bad syntax or validation error (bad_request)
```

**What did you DO? (steps to reproduce)**
1. Run the program with a sample RCM file (see sample file in directory "test-data").
2. Error 400 occurs.

**What's your software environment?**
 - Script language: Python 3.5
 - Operating system: Linux
 - OS version: Ubuntu 16.04 LTS

**Can you provide other helpful information?**
It seems to me that I am missing something in the plugin to make it generate the YNAB header row, but I can't see what's missing. I have compared my plugin with the other two plugins but didn't see anything obvious. 

**Attachments**
See branch [`plugin-RaiffeisenRCM`](https://github.com/bank2ynab/bank2ynab/tree/plugin-RaiffeisenRCM) for sample files.

**Proposed Config**
```
[AT Raiffeisen Bank RCM]
Source Filename Pattern = kta_ei
Source Filename Extension = .dat
Source CSV Delimiter = |
Input Columns = skip,Memo,Date,Payee,Inflow,Memo
Date Format = %Y%m%d
Plugin = RaiffeisenRCM
```

**Sample Data**
```
K|32000|244081|EUR
| POS 6,49 AT K1 09.03. 09:53|20190311|FORSTINGER |-89.30|
| POS 7,96 AT K1 09.03. 10:15|20190311|DER MANN - BACKWAREN|-109.53|
| POS 49,90 AT K2 09.03. 13:04|20190311|BIPA WIEN 1210|-686.64|
| POS 12,87 AT K2 09.03. 13:43|20190311|KIK AUSTRIA FIL. 3220|-177.10|
| HOFER DANKT 0551 K2 09.03. 14:01|20190311| |-983.59|
| SEPA Lastschrift|20190311| Zahlungsempfänger:  S.C.D.|-227.73| Empfänger-Kennung:  LU96KKE12
| POS 4,50 AT K2 09.03. 12:50|20190311|C&A STORE|-61.92|
| SEPA Lastschrift|20190312| Zahlungsempfänger:  John Doe|-2015.88| Empfänger-Kennung:  AT01ZZZ00000123
| ONLINE BANKING VOM 12.03 UM 12:00|20190312| Empfänger:  Dingbats|-1492.99| Verwendungszweck:  09914469
| POS 9,95 AT K2 12.03. 16:08|20190313|DEICHMANN GMBH|-136.91|
| POS 12,40 AT K2 13.03. 13:58|20190313|MCFLY|-170.63|
```

**Comment by nocalla** [comment]
So it's missing the "Date, Payee, Category..." row?

**Comment by torbengb** [comment]
Yes! It's such a small thing to trip me up...

**Comment by nocalla** [comment]
I'm confused as to what this plugin is actually doing. Okay, I can see that the currency conversion is needed, but the other operations seem reasonably standard. 

- The date processing should work without special handling, just provide the correct date format in the conf. 
- The memo concatenation should happen automatically when you provide two identically-named fields. 

What I *think* you need to do is to use the "preprocess_file" function, as per the handelsbanken.py plugin. Can you outline what you want the plugin to do in a stepwise fashion?

**Comment by torbengb** [comment]
_The only thing I need this plugin to do is the currency conversion._ As you can see in the plugin comments, the ATSEUR conversion rate is a fixed value that never changes, so there's no dependency on any external currency provider.

I started this branch because the RCM format requires currency conversion so I figured a plugin is a must. I thought I would try my hand at creating a plugin based on the wiki instructions plus some google-fu. Given my level of Python skills I am fairly satisfied with the result except for this one hurdle.

I am not clear about the interaction between the normal configuration's column mapping and date parsing vs. the plugin's handling of the same. I seems to me that the plugin needs to do this mapping and parsing itself, and that's why I added the logic about concatenating the two memo input columns and doing the date substrings. If all of that is not necessary in the plugin, then all the better. In that case I need to learn those details, and put it in the wiki too.

**Comment by torbengb** [comment]
Edit: apologies, I just noticed that I didn't upload the "nice" version of the plugin, so it doesn't have useful comments. Will fix that tonight!

**Comment by torbengb** [comment]
I now understand that I could use the "preprocess_file" function to convert the amounts _in the source file_ and then let the normal b2y program do its magic. That seems to be a more focused approach. I didn't grasp this function, I just started with a copy of the template, and the "preprocess_file" function isn't in there. 

I'll have another go at the plugin, from scratch based on the handelsbanken.py plugin. Thank you for this guidance!

**Comment by nocalla** [comment]
I *think* that approach makes sense anyway! Give it a try and see how you get on.

**Comment by torbengb** [comment]
I'm pushing the RCM plugin now _before_ I make the switch to "preprocess_file".

**Comment by torbengb** [comment]
Hey, I am not grokking this. 

I have pushed a debug file:
https://github.com/bank2ynab/bank2ynab/blob/plugin-RaiffeisenRCM/RaiffeisenRCM-debug.py
that can run on its own using the test data file. It generates an output file which has the original columns in the original order and the currency conversion has taken place (YAY!) but it's formatted wrong and I can't get that to work. 

- each row is bracketed, 
- each field is quoted,
- it's not UTF-8 so umlauts are kaput.

I felt I was closer to my goal with the previous attempt: just missing the header row, and I think I have understood enough Python now that I can make that work, but it's bedtime. It's frustrating that the preprocessing _should_ be simpler but it's stumping me even more than the first attempt.

**Comment by torbengb** [comment]
Whew ... I went back to the previous attempt and hard-coded the header line into the plugin. Et voilà: now it works!
I'll make a pull request and get some feedback before it's integrated into /develop.

**Comment by torbengb** [comment]
Tests passed =>merging and closing.
