### ISSUE TITLE
I've created a web app that lets you convert all kinds of files into a YNAB-friendly format using the configs provided by bank2ynab and my own scripts.

### ISSUE THREAD

**Issue by leolabs** [bank2ynab/bank2ynab#270]
The project is hosted here: https://ynap.leolabs.org/
The source code is available on GitHub: https://github.com/leolabs/you-need-a-parser

I wrote a script that converts your configuration format into JSON which can more easily be parsed in JS and other languages: https://github.com/leolabs/you-need-a-parser/blob/master/scripts/fetch-bank2ynab.ts

The converted config file is available [here](https://github.com/leolabs/you-need-a-parser/blob/master/src/parsers/bank2ynab/banks.json). I've excluded bank formats that need a plugin to work and formats that I've already implemented myself.

It may be nice to have a list of projects using your configs in this repo so that projects like this could be linked.

**Comment by nocalla** [comment]
- This is great, glad you were able to get some benefit from our mild obsession!
- I wonder could we automate that JSON conversion and put it in a pre-commit so the data is readily available...
- That's a **great** name!

**Comment by leolabs** [comment]
Thanks! I've extracted my script to generate the JSON config into a separate NPM package called [ynap-bank2ynab-converter](https://www.npmjs.com/package/ynap-bank2ynab-converter) ([source code](https://github.com/leolabs/you-need-a-parser/blob/master/packages/ynap-bank2ynab-converter/src/index.ts)). It fetches the current bank2ynab config from a given branch of your repo (default: master) and generates the JSON config. You can easily run it like this, given that you have node, npm, and npx installed:

```
$ npx ynap-bank2ynab-converter
```

If you want to use the tool pre-commit, I can include an option to provide a local config file instead of the GitHub branch.
