### ISSUE TITLE
More helpful API error messages

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#273]
**Is your feature request related to a problem? Please describe.**
The API error messages are rather generic and I think we can improve them - in particular the error 401 `API access token missing, invalid, revoked, or expired` ([link to code line](https://github.com/bank2ynab/bank2ynab/blob/develop/bank2ynab.py#L883)) because users are very likely to encounter this error on their first try of the new API-enabled bank2ynab.

**Describe the solution you'd like**
The error messages should be longer. In particular, they should not only describe the problem but also describe possible solutions and/or link to our wiki and/or the YNAB (API?) help pages for details. 

**Describe alternatives you've considered**
A first step is to provide a little guidance right in the error message.

**Additional context**
Relevant link for the 401 error: https://api.youneedabudget.com/#personal-access-tokens 

I prefer to link directly to YNAB pages because then we don't have to maintain our own wiki page and run the risk of it being outdated. OTOH a wiki page can contain anything we want!

**Comment by nocalla** [comment]
A relevant issue #395 has flagged some potential improvements.

https://github.com/bank2ynab/bank2ynab/issues/395#issuecomment-889116170
