### ISSUE TITLE
Remember format/budget link

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#275]
**Current**

The new sweet API integration cleverly remembers what account a file is mapped to. 

**Describe the solution you'd like**
Since we already link any given input format to a specific account, we should also link each input format to a specific budget. 

**Describe alternatives you've considered**
Downsite is that the API feature can't yet handle if one format is used for more than one budget. This is already the case: it can't handle if a format is used for more than one budget. So it's no worse than we already are. 

Perhaps later the program should not only ask what budget&account to map to, but also whether to remember this - so the user has the choice to say no if they really have the same format for several budgets/accounts.

**Comment by nocalla** [comment]
It's a good point. Reasonably trivial to code. I don't want to properly implement it until we have more API stuff sorted out though just to avoid hassle while developing though!

**Comment by nocalla** [comment]
(don't want to mess up my own budget by accident!)

**Comment by torbengb** [comment]
Yes I thought I should create a dummy budget for testing. I am brave
(stupid?), and didn't take this precaution. Haven't broken my budget yet!

**Comment by nocalla** [comment]
I think I'm ready to go ahead with this, I've used the API successfully for several months.

**Comment by nocalla** [comment]
This fix is messier than I thought it would be! Forgot how ingrained the concept of a "default" budget was in the code!
