### ISSUE TITLE
User config keeps getting reset to default

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#276]
**Describe the bug**
Every time I grab a fresh copy of bank2ynab and put it where my existing files (and user config) live, the user config is overwritten with the default user config. I have to re-add my default file path, API key, and so on.

**What did you EXPECT to happen?**
My own edited user config should remain untouched.

**Can you provide other helpful information?**
It seems obvious to me that our package should not contain a file called `user_configuration.conf`. Should we provide `user_configuration.conf.template` instead?

**Comment by nocalla** [comment]
Seems reasonable.

**Comment by torbengb** [comment]
I've renamed the file, in develop and in the API branch.

**Comment by nocalla** [comment]
This has created a merge conflict in the pull request. I would not have renamed it in both branches - make a change in one branch, then merge it to another. Otherwise git can't keep up!

**Comment by nocalla** [comment]
Fixed the merge conflict.

**Comment by nocalla** [comment]
Oddly, this change is causing an error in the testing now. 
`configparser.NoOptionError: No option 'ynab api access token' in section: 'DEFAULT'`

It *shouldn't* because the main conf file has that option in Default...

**Comment by torbengb** [comment]
First, apologies for the goof of renaming in both branches.

Second, I have an idea: it there a space after the equal sign in the
config? I had trouble with that once, and removing it might help. (Deal
with trimming of parameters later).

**Comment by nocalla** [comment]
So this is an interesting study at how seemingly-unrelated things can affect each other. I had a hard-coded reference to user_configuration.conf at the start of the API class to ensure that the output of account saving went to the correct place. Obviously this isn't optimal, but it requires a lot of changing around to fix the behaviour.

**Comment by nocalla** [comment]
Fixed error raised by this hard-coding!

**Comment by torbengb** [comment]
I am curious how you solved this, I'll have a look at the code later. I think hardcoding the user file name was fine so I am not sure what problem you encountered.

I'm just curious, for my own learning, not disagreeing with any change you make/made.

**Comment by nocalla** [comment]
The issue was where and how I coded it. In the API class I was *just* reading from the user config for the whole class so that when the account automatically saved, it didn't write the entire config file to the user_conf. I've changed it to use the normal combined config for most of it, but just to use the user one in the save_account_selection function.
