### ISSUE TITLE
NO Sparebank: outflow column is imported as inflow

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#281]
**Describe the bug**
A friendly user submitted this bug report to me by email:  
I just got a chance to try this out, and even though the CSV output seemed to be correctly formatted, when i  imported into YNAB,  the inflow and outflow category were mixed and everything landed in inflow. Can this have anything to do with outflow values being presented as negative in my banks CSV? Example an outflow of -100 might make YNAB think i really had an inflow of 100, as its practically a double negative.

**What did you EXPECT to happen?**
Any value in the outflow column should always be imported as a YNAB outflow. It should not matter if there is a minus sign or an (implicit) plus sign for that value.

**What ACTUALLY happened?**
A positive value in the outflow column gets imported correctly as a YNAB outflow.  
A **negative** value in the outflow column gets imported **incorrectly** as a YNAB **inflow**. 

**What did you DO? (steps to reproduce)**
1. Have any YNAB CSV file with any transaction whose inflow column is blank and outflow column has any value **with a leading minus sign.**
2. Import that file.
3. Note that the transaction gets imported as an inflow. This should be an outflow.

**Comment by torbengb** [comment]
I think the fix could be very simple: the normal bank2ynab processing should take the 

We already have [this bit of code that converts a negative inflow into a positive outflow](https://github.com/bank2ynab/bank2ynab/blob/develop/bank2ynab.py#L394). We should duplicate this function to a new one that that converts a **negative outflow** into a **positive outflow**.

**Comment by nocalla** [comment]
This is likely caused by the handling of banks that only have one column for inflow and outflow. This will be non-trivial to fix in the code, perhaps we can rearrange the config for this bank instead. I would suggest calling both columns Inflow and testing the data to see if that works.

**Comment by nocalla** [comment]
Actually, @torbengb, that piece of code you linked only targets the inflow column. It doesn't modify the outflow section. This is down to how YNAB itself handles the minus sign in cells. My proposed fix about modifying the config column names should work to fix this, as negative inflow is converted to outflow.

**Comment by torbengb** [comment]
*"calling both columns Inflow"* is an interesting test, and would work of course. Only downside I see is that it would need to be configured with every relevant format.

I'd still like to try the generic approach by duplicating the `_fix_outflow` function, specifically making use of the [line 450](https://github.com/bank2ynab/bank2ynab/blob/develop/bank2ynab.py#L450) and making it test for `if(outflow.startswith("-")):`. 

This generic approach eliminates the risk that would be when we forget the trick with having two inflows. I like it because it makes the whole thing more idiot-proof :-) although I haven't tried implementing that yet. It might not be as simple as I think, and then we still have the two-inflow trick as a fallback.

**Comment by nocalla** [comment]
I disagree. I think it's a reasonable approach to convert a negative column into a positive of its opposite (as does YNAB apparently!). I think this bank is the less common approach. If we change this, we'd probably have to implement a "convert negative outflows to inflow" flag.

**Comment by torbengb** [comment]
Fair enough. I understand your argument; a negative inflow is *clearly* an outflow. By inference, you say a negative outflow is an inflow. I agree that's consistent, but to me it's not a given. 

Anyway - I'll do the two-inflow config change now. If this issue happens more frequently, I might want to revisit this discussion, but for now it's a one-off.
