### ISSUE TITLE
Match format to file when file name is not unique

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#283]
**Is your feature request related to a problem? Please describe.**
The tool now contains four different formats that all share the same file name "export.csv" and this means that the tool can't pick the right format. 

**Describe the solution you'd like**
The tool should be enhanced so that it doesn't (only!) rely on the file name. 

**Describe alternatives you've considered**
The current workaround is that affected users have to edit their copy of "bank2ynab.conf" to disable or remove the formats that mismatch on their file name.

**Additional context**
These formats have non-unique file names:

- [BE Keytrade Bank]
- [DK Sparkassen Thy]
- [SE Nordea]
- Source Filename Pattern = export

**Comment by nocalla** [comment]
I think that this would require a lot of overhead. What criteria do you use to compare?

**Comment by torbengb** [comment]
I don't have a finished idea in my head, but I guess that bank2ynab would have to "taste" the file with each potential format and see if the columns match up; if they don't then try the next format?
 
I agree this sounds like a big change, so I don't see us diving into this anytime soon. But at least the issue needs to be noted. And possibly closed as wont-fix?
