### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by rogerolden** [bank2ynab/bank2ynab#290]
*Dear submitter, please edit the following according to your needs. Thank you!*

**Describe the bug**
I get the following response in Terminal: 

"Traceback (most recent call last):
  File "./bank2ynab.py", line 28, in <module>
    import requests
ModuleNotFoundError: No module named ‘requests'"

**What did you EXPECT to happen?**
I expected the .CSV file to be exported and reformatted for YNAB

**What ACTUALLY happened?**
I got an error in my terminal.

**What did you DO? (steps to reproduce)**
1. First I downloaded the develop version from here https://github.com/bank2ynab/bank2ynab/archive/develop.zip
2. Then I moved it into my documents folder on my Mac (which is synced to iCloud using iCloud Drive.
3. And then I open the file "bank2ynab.conf" in a TextMate 2 and #commented  all lines that read "Source Filename Pattern = export" besides the one relevant for my bank Nordea.
4. Then I CD into the correct folder.
5. And then I run the script using the command python3 ./bank2ynab.py
6. I also configured the python file to look for the .CSV in the correct folder.

**What's your software environment?**
 - Script language: Python 3.7.4
 - Operating system: MacOS?
 - OS version: 10.14.6

**Can you provide other helpful information?**

**Attachments**
If applicable, add sample files or screenshots to help explain your problem.

**Comment by nocalla** [comment]
Ah, you're missing the Requests dependency. Apologies, haven't updated the dependencies yet. Do you have pip set up? There's a requirements.txt file if you do. Otherwise, install the requests library.
