### ISSUE TITLE
Allow for different date format languages

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#300]
**Describe the bug**
As per @blinkiz in #297:
> If source date format is like '16 Oktober 2019' and 'Oktober' is spelled in another language then your current LC_TIME, then you need to change date format language.Valid inputs are 'sv_SE.UTF-8', 'en_US.UTF-8' or whatever your operating system understand as LC_TIME variable.

**What did you EXPECT to happen?**
Date should be recognised and processed appropriately.

**What ACTUALLY happened?**
Incorrect date parsing.

**What did you DO? (steps to reproduce)**
Bank with source format using non-English words is not recognised.

**Can you provide other helpful information?**
The LC_TIME variable is unreliable and varies depending on operating system. I think @blinkiz's fix in #297 should not be used as a result of this. I think we need to implement a generic plugin to handle different specifically-listed formats and call this for the banks that require it.

**Comment by blinkiz** [comment]
Hello. Here is an example csv file with Swedish date format (sv_SE.UTF-8). It is an export from Revolut with the filename "Revolut-SEK-Statement-okt. – nov. 2019.csv".
https://privatebin.net/?5e0d91ab43cb81b2#6uXFidYwy5kMbvZf2sQ5aGeg2nNtZbGEwtjAxn2RiJ3N

I have set it to expire this paste in one day so please download it. It has been anonymized and the amounts has been changed but it is unnecessary to have it laying around on the Internet. let me know if you need me to upload it again.

**Comment by nocalla** [comment]
Completed Date ; Description ; Paid Out (SEK) ; Paid In (SEK) ; Exchange Out; Exchange In; Balance (SEK); Category; Notes
3 nov. 2019 ; Aardvark ; 122,22 ; ; ; ; 77 777,77; aggravating medical problems; 
3 nov. 2019 ; Catamaran; 23,65 ; ; ; ; 88 888,88; toenails;
