### ISSUE TITLE
Swedbank import bug

### ISSUE THREAD

**Issue by Stonedestroyer** [bank2ynab/bank2ynab#301]
*Dear submitter, please edit the following according to your needs. Thank you!*

**Describe the bug**
Swedbank SE 2019 is currently broken as nothing is outputted. 

**What did you EXPECT to happen?**
Results to show in the file.

**What ACTUALLY happened?**
No actual numbers or names in the file.

**What did you DO? (steps to reproduce)**
1. Go to swedbank.se and get a exported csv file and try to import it. It tries to import 4 different banks before that one so I changed in section name but it did not help. 

**What's your software environment?**
 - Script language: Python 3.5, Python 2.7, other?
 - Operating system: Windows, Linux, MacOS?
 - OS version:

**Can you provide other helpful information?**

**Attachments**
If applicable, add sample files or screenshots to help explain your problem.

**Comment by Stonedestroyer** [comment]
The issue seems related to when exporting a date related export where date is not shown.

**Comment by torbengb** [comment]
Hejsan! 

What is the default file name of the Swedbank CSV file? "bank2ynab" thinks it should be "exported.csv", can you confirm this? There's no other format with that file name, so I'm not sure what you mean with "tries 4 different banks", can you clarify that for me please?

Could you add 1 sample data row from your Swedbank CSV file? This will help me check that the format conversion matches the input CSV format.

You mention that "date is not shown", can you describe when that happens? Do you have any rows in the exported file that are normal transactions but they have no date?

**Comment by nocalla** [comment]
If there's no date on the line, then YNAB can't handle it, so Bank2YNAB just skips that row and keeps going.

**Comment by Stonedestroyer** [comment]
Seems to be a bug with the Swedbank site then as it gives no date.

**Comment by nocalla** [comment]
So how do you know when each transaction was??

**Comment by Stonedestroyer** [comment]
I will close this issue cause it seems like their export by range doesn't add the date, seems like a bug on Swedbank. And you don't.

**Comment by nocalla** [comment]
That's a shame. Let us know if that changes and we can include the updated format.
