### ISSUE TITLE
API-created transactions don't use Payee matching

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#306]
**Is your feature request related to a problem? Please describe.**
- Importing via CSV generates a lot of duplicate payees, e.g. "Amazon 446", "Amazon 447", and so on. Evidently, the Payee Renaming Rules are not taking effect. [example screenshot](https://support.youneedabudget.com/t/x1rpy9/no-payee-matching-for-api-created-transactions)
- According to [this support response](https://support.youneedabudget.com/t/x1rpy9/no-payee-matching-for-api-created-transactions), Payee Renaming Rules are only processed for imported transactions.  A transaction is only considered imported if it has an import_id specified.

**Describe the solution you'd like**
"bank2ynab" should always send an `import_id` (char 36) for every transaction. 

**Describe alternatives you've considered**
I seem to recall we've discussed this somewhere already but can't find it. There were some caveats that we need to figure out - or test whether they are in fact a problem?
- If we assign any random `import_id` to every transaction, then there would be duplicate entries in YNAB after uploading two overlapping CSV files. 
  - E.g. if I imported a file yesterday and another one today then the newer one includes transactions that were already present in yesterday's import - but today's import provided new `import_id`s so they probably appear as two distinct transactions in YNAB?

**Comment by nocalla** [comment]
An import_id *is* created for each transaction. 

`import_id format = YNAB:amount:ISO-date:occurrences`

For me, the payee renaming rules *do* work for API-created transactions - is it something to do with how the rules are set up in YNAB?

**Comment by torbengb** [comment]
Oh, you're up late :-) 
I wonder - I have some pretty basic rules that don't get triggered. I'll do some tests on my side (I have the latest state of bank2ynab/develop).

**Comment by nocalla** [comment]
Your example screenshot link is not a link to a screenshot, can you update so I can see what's happening? It might be helpful to show the rule in question too.

**Comment by torbengb** [comment]
The screenshot link was meant to just be the first image in Dmitriy's post. Here's a direct image link: https://s3-us-west-2.amazonaws.com/media.forumbee.com/i/f7f5c160-3069-4096-ae93-7b7108255da5/547.png

**Comment by torbengb** [comment]
My rule just says "contains amazon". Let me test and make some screenshots of my own to share.

**Comment by nocalla** [comment]
I just tested with my two banks for December so far and all my YNAB renaming rules worked fine.

**Comment by nocalla** [comment]
Any further update on this, @torbengb?

**Comment by nocalla** [comment]
Hey @torbengb - any further update on this?

**Comment by nocalla** [comment]
#405 is a relevant pull request for more customisable payee mapping.
