### ISSUE TITLE
GitHub "Actions"? --> 

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#307]
**Is your feature request related to a problem? Please describe.**
GitHub has added a new kind of thing that apparently automates the Python packaging process?   
https://github.com/bank2ynab/bank2ynab/actions/new

**Describe the solution you'd like**
We should look into how we could leverage that for this project.
I'll put it on my list and see when I get around to it.

**Comment by nocalla** [comment]
Oh this looks cool. Especially:

```
Publish Python Package
Publish a Python Package to PyPI on release.
```

**Comment by nocalla** [comment]
...I am having fun with this feature.
