### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by eostman** [bank2ynab/bank2ynab#310]
**Describe the bug**
While following the instructions of the [User guide ](https://github.com/bank2ynab/bank2ynab#user-guide) in step 3 you are supposed to run python 3 ./bank2ynab.py.

When doing this, the following error happens:
```
Traceback (most recent call last):
  File "./bank2ynab.py", line 28, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
Seems to only happen in the latest version. Tested that the error is not raised for version 1.1.0

**What did you EXPECT to happen?**
That the script would run without throwing a missing module
**What ACTUALLY happened?**
Either a step in the user guide is missing or you need to supply the module also in the ZIP file somehow

**What's your software environment?**
 - Script language: Python 3.7.6
 - Operating system: MacOs
 - OS version: Catalina

**Comment by nocalla** [comment]
Hi @eostman, thanks for flagging this. A step is missing in the installation instructions. Try the following in your command line and it should install the missing module. 
`pip install -r requirements.txt -f`

**Comment by ferryrs** [comment]
I have this same problem. **When I do this: "pip install -r requirements.txt -f"**

I get the following error:
-bash: pip: command not found

**If I try: "pip3 install -r requirements.txt -f"**

I get the following error:
"Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

-f option requires 1 argument"

**Comment by ferryrs** [comment]
**pip3 install -r requirements.txt** seems to work. Where was the **-f** function for?

**Comment by nocalla** [comment]
I actually can't find my original reference for that -f! I'll update my post above.
