### ISSUE TITLE
Support for Holvi (Business Account)

### ISSUE THREAD

**Issue by konstantinkopka** [bank2ynab/bank2ynab#321]
I did not see Holvi listed in the list of supported Bank formats. It's a rather new freelancer focused fintech bank. Would like to use bank2yanb for this. Does anyone have any experience with it?

**New bank format: Holvi**
- Full name of the bank: Holvi
- Country (2-character country code): FI

```
Source Filename Pattern = UNKNOWN
Source Filename Extension = UNKNOWN
Use Regex for Filename = UNKNOWN
Source CSV Delimiter = UNKNOWN
Header Rows = UNKNOWN
Footer Rows = UNKNOWN
Input Columns = UNKNOWN
Date Format = UNKNOWN (see http://strftime.org/ for date format strings)
```

**Comment by nocalla** [comment]
Hi @konstantinkopka, can you provide the details of the format of the bank export file? I've provided the types of details we're looking for below. We can use these details to support the bank. 

Source Filename Pattern = my_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Header Rows = 1
Footer Rows = 0
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Date Format = (see http://strftime.org/ for date format strings)

**Comment by nocalla** [comment]
Insufficient information provided, closing until more information provided.

**Comment by konstantinkopka** [comment]
> Insufficient information provided, closing until more information provided.

Hi, sorry for the super late reply.

The Holvi files unfortunately come in .xls format, is it possible to convert .xls files at all?
I went ahead and converted the .xls file to .csv format and will provide you with details:

```
Source Filename Pattern = accountnumer-journal-2020-03-22_00_00_00
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Header Rows = 5
Footer Rows = 0
Input Columns = Date,Type,Subcategory,Category,Payee,Description,AdditionalInfo,Outflow,Inflow
Date Format = %d.%m.%y, %H:%M
```


Here is an example .csv file (edited of course)

```
JOURNAL,,,,,,,
,,,,,,,
Name,,,,,Datum,,22.03.20
PersonalInformation
,,,,,,,
Zeit,Art,Subkategorie,Kategorie,Sender / Empf�nger,Bezeichnung,Zus�tzliche Informationen,SUMME
"11.03.20, 15:51",income,iban_payment,Unkategorisiert,DescriptionTextInflow,,1000
"12.03.20, 09:08",expense,outboundpayment,Unkategorisiert,DescriptionTextOutflow,-500
"12.03.20, 09:08",expense,outboundpayment,Unkategorisiert,DescriptionTextOutflow,-500
```

**Comment by nocalla** [comment]
At the moment, we don't have an .xls converter plugin. Thanks for the information though.
