### ISSUE TITLE
[NL] ING Bank 2020 inflow and outflow swapped

### ISSUE THREAD

**Issue by ferryrs** [bank2ynab/bank2ynab#327]
The recently updated ING Bank 2020 format leaves the inflow and outflow swapped.

**Comment by torbengb** [comment]
Unsure of this bug report. The new format as mentioned in issue #320 is identical to the earlier version except for the file name, so the credit/debit flag is parsed the same. 

@ferryrs could I ask you to test this again without changes please? And then make the wollowing change to the `bank2ynab.conf` file and then do a new test as comparison.

In the configuration file, change the [line 476](https://github.com/bank2ynab/bank2ynab/blob/develop/bank2ynab.conf#L476):  
`Inflow or Outflow Indicator = 5,Af,Bij`  
to:  
`Inflow or Outflow Indicator = 5,Bij,Af`

**Comment by nocalla** [comment]
@ferryrs can you also post a few sample lines of the CSV file please? If you just paste the first few lines in (obviously change any personal details) that would help us identify any format changes.

**Comment by ferryrs** [comment]
@nocalla Input:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/57290903/73520422-e5d8c200-4403-11ea-9bc8-4622d7f291f0.png">
Af = outflow
Bij = inflow

Output (before fix):
<img width="417" alt="image" src="https://user-images.githubusercontent.com/57290903/73520508-16b8f700-4404-11ea-9747-bd3b6920611f.png">

@torbengb doing what you said, did fix the issue.

**Comment by nocalla** [comment]
Thanks, @ferryrs, obviously our initial survey was not filled out correctly!
