### ISSUE TITLE
Support Fiducia Banks (Volksbank, Sparda-Bank, PSD, ...)

### ISSUE THREAD

**Issue by M4a1x** [bank2ynab/bank2ynab#328]
**New bank format**
- Full name of the bank: Fiducia Banks (Volksbank, Sparda-Bank, PSD, ...)
- Country (2-character country code): DE

**NOTE**: The Fiducia IT is a company responsible for the IT infrastructure of a lot of german "Genossenschaftsbanken". These include the above mentioned ones and more. As I currently only have access to "Sparda-Bank Südwest" the export format might differ with differ slightly with different banks.
I also found [this ynab converter project](https://bitbucket.org/ctheune/ynab-bank-imports/src/default/src/ynab_bank_import/fiducia.py) also implementing fiducia, suggesting that indeed it is the same format for all banks.

I'm planning on issuing a pull request on this.

```
[DE Fiducia (Volksbank, Sparda-Bank, BBBank, PSD Bank, ...)]
# Only tested with Sparda-Bank
Use Regex For Filename = True
Source Filename Pattern = Umsaetze_[A-Z]{2}\d{20}_\d{4}.\d{2}.\d{2}
Source CSV Delimiter = ;
Header Rows = 12
Footer Rows = 3
Input Columns = Date,skip,skip,Payee,skip,skip,skip,skip,Memo,skip,skip,Inflow,CDFlag
Date Format = %d.%m.%Y
Inflow or Outflow Indicator = 12,H,S
```

**Comment by M4a1x** [comment]
How would I go about adding tests for it with the test file I posted in #330 as you suggested? 
I found test_read_data in the `test_B2YBank.py`. Am I correct in that I would have to add the .csv to `test-data` and copy the configuration for the bank from `bank2ynab.conf` to `test-data/test.conf`?

**Comment by nocalla** [comment]
All you need to do is add a sample anonymised CSV file to the test-data folder. We don't currently have automated testing of all the bank formats, but it could be a helpful reference for someone in the future.
