### ISSUE TITLE
Prøvet med Nordea

### ISSUE THREAD

**Issue by thorwinther** [bank2ynab/bank2ynab#337]
Hej
Det virker fint for Nordea, men jeg skulle selv finde ud af 3 ting.

1. Jeg skulle putte "# -*- coding: utf-8 -*-" øverst i /plugins/JLP_Card_UK.py
2. "user_configuration.conf" fandtes ikke - lavede den selv fra template
3. Jeg skulle ændre "bank2ynab.conf" for Nordea til:

```
[DK Nordea]
# source: Issue #92
Source Filename Pattern = **poster**
# The default filename is unknown! Please submit an issue if you know the name! See details here:
# https://github.com/bank2ynab/bank2ynab/wiki/MissingDefaultFilename
Source CSV Delimiter = ;
Input Columns = Date,Payee,skip,Inflow,skip
Date Format = %Y-%m-%d
```

Filerne fra nordea hedder "poster.csv"

**Comment by nocalla** [comment]
`Hi It works fine for Nordea, but I had to figure out 3 things myself. I should put "# - coding: utf-8 -" at the top of /plugins/JLP_Card_UK.py "user_configuration.conf" did not exist - made it myself from template I should change "bank2ynab.conf" for Nordea to`

Google translate version of above! Sorry, I don't speak Danish! 

- You shouldn't need to do anything to the plugin, this bank doesn't use that plugin
- user_configuration.conf doesn't exist by default - there's a template file that you can use to create it if you wish, but you shouldn't need to use it unless you're doing the YNAB API upload
- Thank you for the default filename!

Adding the following to the configuration file as the new format:

```
[DK Nordea]
# source: Issue #92
Source Filename Pattern = poster
Source CSV Delimiter = ;
Input Columns = Date,Payee,skip,Inflow,skip
Date Format = %Y-%m-%d
```

**Comment by nocalla** [comment]
Thanks for the contribution!

**Comment by thorwinther** [comment]
Hello
I understand the plugin is for a different bank, but even so the program
wouldn't run before I added that.
Just letting you know :)

Ran with python 2 from powershell

Also, I used the user conf file to set up different path for csv files than
default



Thor

**Comment by nocalla** [comment]
Ah okay. We're not supporting Python 2 any more, so maybe that's why there's some strangeness with utf encoding.

**Comment by thorwinther** [comment]
I understand.

Python 3 gave me some errors that I didn't bother debugging so I just ran
python 2

Thor
