### ISSUE TITLE
AU ING not parsing any lines

### ISSUE THREAD

**Issue by zirophyz** [bank2ynab/bank2ynab#356]
When attempting to parse AU ING Transactions.csv file, no lines are processed.

Output from bank2ynab.bat;

Parsing input file:  C:\Bank\Transactions.csv (format: AU ING)
INFO: Using encoding ascii with confidence 1.0
INFO: Using encoding ascii with confidence 1.0
INFO: Parsed 0 lines
INFO: No output data from this file for this bank.
INFO:
Done! 1 files processed.

Sample data:

Date,Description,Credit,Debit,Balance
02/07/2020,ONLINE STORE - Visa Purchase - Receipt 123456In TOWN Date 30 Jun 2020 Card 123456xxxxxx1234,,-85.00,429.24
29/06/2020,"PERSON NAME  - Osko Payment - Receipt 123456 ",130.00,,514.24
27/06/2020,MyDescription - Internal Transfer - Receipt 12345 Orange Everyday 1234567890,,-14.00,384.24
27/06/2020,MERHCANT NAME - Visa Purchase - Receipt 123456In SOUTH TOWN Date 25 Jun 2020 Card 123456xxxxxx1234,,-6.30,398.24

**What's your software environment?**
 - Script language: Python 3.8
 - Operating system: Windows
 - OS version: 10

It didn't seem like the default Input Columns matched in bank2ynab.conf so I attempted with;
Input Columns = Date,Memo,Inflow,Inflow,skip
Input Columns = Date,Payee,Inflow,Inflow,skip

**Comment by nocalla** [comment]
So the below is the current config for this bank.

```
[AU ING]
# Transactions.csv
Source Filename Pattern = Transactions
Header Rows = 1
# Double 'Inflow' looks strange but is correct
# The input csv uses 2 seperate columns, but has positive values
# for the inflows and negative values for the outflows
# The conversion will take those negative inflows and convert them to outflows
Input Columns = Date,skip,Payee,Inflow,Inflow
Date Format = %d/%m/%y
```

I think we're probably looking at an issue with the "double inflow" section. Did tweaking those values as you outlined work?

**Comment by nocalla** [comment]
`Date,Payee,Inflow,Inflow,skip` should work I would think. Alternatively, try `Date,Payee,Inflow,Outlow,skip`

**Comment by zirophyz** [comment]
Both suggestions still didn't pick up any lines from the csv.

**Comment by zirophyz** [comment]
Oh boy it was the date format that was incorrect.

It needed to be Date Format = %d/%m/%Y to account for 4-digit year.

The input columns need to be adjusted to Date,Memo,Inflow,Inflow,skip.  Or, just Date,skip,Inflow,Inflow,skip.  I guess this can be changed on user preference.  I'm not sure how to use Git to update the date format.

**Comment by nocalla** [comment]
Ah, great news. I'll make the update before the end of the week when I get a chance. Thanks for the contribution.
