### ISSUE TITLE
Integrating bank2ynab into the YNAB app?

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#359]
_Breaking: YNAB (the company) might consider integrating b2y into YNAB (the app)?!_  I asked in their current "Reddit: ask me anything" session and YNAB/Todd said they'd be open to talks. Rather than me just running with it, I think the team would appreciate an open discussion first. Here's the thread:

> **Question:** What plans do you have for getting better at importing non-ynab-formatted CSV's into the app? Will you ever consider "absorbing" one of the community tools (we'd love that), or in some other way embrace what we're doing?

> **Answer:** I'd be the first to say our CSV import is not an ideal experience—and it's been the same basic implementation for a long time. So sure, we'd consider it. I can't say we really have, so there may be complications I'm not thinking of in my third hour of an AMA ... but I'd love to talk more. Shoot me an email [help--youneedabudget.com]. 

https://www.reddit.com/r/ynab/comments/hsddx2/my_name_is_todd_curtis_im_the_cpo_at_ynab_ama/fya8pq5/?context=1

**Discussion items**

1. Do we want to discuss this, or would the b2y core team vehemently reject the idea? I wrote "we'd love" for our project to be absorbed into YNAB. Is that even true? It would be a cool achievement, but we'd also lose control of how this tool works. 

1. I thought about chatting in Gitter but on the other hand, these issues get sent out by email to us which might be easier? (I for one won't have Internet access except for emails the coming few weeks.) Is this Github issue a useful place/medium to discuss this topic? Suggestions welcome.

1. If we do decide to pitch this to YNAB (the company), the first correspondence needs to be brief and powerful. Do you want to be involved in drafting it? How?

1. Am I making too much out of this? There's a chance that YNAB/Todd got my hopes up but it will end up being too much for them to actually take onto their roadmap. As he said, it's been this way for years now.

Discuss.

**Comment by toyg** [comment]
Thanks for the ping, but I've not been involved for ages and this is really your baby, guys :) so your call really. I think an issue tracker is a bit too public for this sort of thing, but anyway...

I think you have to first figure out what the ideal (but realistic) scenario is for *you*. 

They don't ship desktop apps anymore and I'd be willing to bet they don't want to ship any utility either; so the only option I see for "absorbing" b2y, from their perspective, is to run it on their servers with a web interface on top; but I think they'd soon find that hacky and just rewrite it in-house. You _might_ leverage that into a job if you fancy it, but do you want it?

The easiest option is to ask for a shout out somewhere, making it "unofficially official". They have a link to [this tool](https://aniav.github.io/ynab-csv/) on [this page](https://docs.youneedabudget.com/article/921-importing-a-csv-file). It's a bit of glory, but might result in more support tickets.

I don't see what else they could realistically do with this code.

**Comment by nocalla** [comment]
I've no interest in getting a "job" out of this. If they want to use the bank format info we've got, they are welcome to. Maybe there's a way we can present the bank information to them that we've gleaned, but - as @toyg says - they won't use our code. I am not a professional programmer by any means and this project is a way for me to learn. I agree that getting the "shout-out" would be nice, but at the end of the day, I wrote the original version of this as a means for me to get *my* transactions into YNAB - anything extra after that is just icing. 

1. If they absorb it in a way that it'll work, that's good. I can't see them wanting to waste resources on maintaining the conf though.
2. Github issues works better for me.
3. Nope.
4. As said above, I can't see them actually wanting to use our hacky python code! I don't know what language YNAB is written in, but I guarantee that we do not conform to their internal code standards!

**Comment by torbengb** [comment]
Thanks for your replies, guys. I agree with you that they would not be
using our code, per se, but I believe that the basic design is both good
and clever. YNAB is built on Ember, meaning Javascript, so they would have
to write it from scratch anyway.

But @nocalla don't make light of the code. You say it's hacky, but it works
well for a lot of people, and it fiils a need for them as well as for us.
You might not be a rockstar developer, so what? You built the basis
practically by yourself, and I for one am very grateful for that.

Still - they won't use our exact code, but if we can get them to do
*something* then it's better than what the app has today.

I'll get in touch with them and see if they are really interested in doing
anything at all, then take it from there.

-Torben
