### ISSUE TITLE
Swedbank

### ISSUE THREAD

**Issue by Stonedestroyer** [bank2ynab/bank2ynab#360]
*Dear submitter, please edit the following according to your needs. Thank you!*

**New bank format**
*If you're submitting something else, skip or remove this section and continue below.*
Swedbank 
Sweden

CSV, and filename is Transaktioner_2020-07-31_17-07-11.csv

```
* Transaktioner Period 2020-01-01–2020-07-31 Skapad 2020-07-31 17:07 +02:00
Radnummer,Clearingnummer,Kontonummer,Produkt,Valuta,Bokföringsdag,Transaktionsdag,Valutadag,Referens,Beskrivning,Belopp,Bokfört saldo
1,XXXXX,XXXXXXXX,"Privatkonto",SEK,2020-07-31,2020-07-31,2020-07-31,"PAYPAL *NAMECHEA","PAYPAL *NAMECHEA",-30.40,1407

```

**Comment by nocalla** [comment]
Hi @Stonedestroyer, thanks for the contribution. We already have a configuration for this bank - I assume this no longer works considering that your input doesn't match the format we have already.

```
[SE Swedbank]
# source: Issue #134
# exported.csv
Source Filename Pattern = exported
Header Rows = 2
Footer Rows = 3
Input Columns = skip,skip,Date,Payee,Memo,Inflow,skip,CDFlag,skip,skip,skip,skip,skip,skip,skip
Inflow or Outflow Indicator = 7,K,D
Date Format = %Y/%m/%d
```

**Comment by nocalla** [comment]
Proposed updated Config below. Can you test this with a transaction file and see if it works please? I've uploaded this change to the branch referenced in this pull request: #361

```
[SE Swedbank 2020]
Use Regex For Filename = True
Source Filename Pattern = Transaktioner_20([0-9]{2}-){2}[0-9]{2}_([0-9]{2}-){2}[0-9]{2}
Header Rows = 2
Input Columns = skip,skip,skip,skip,skip,Date,skip,skip,Payee,Memo,Inflow,skip
Date Format = %Y-%m-%d
```

**Comment by Stonedestroyer** [comment]
Not sure I did something wrong.


```py
(.venv) C:\Users\stonedestroyer\Downloads\bank2ynab-feature-360_Swedbank_SE\bank2ynab-feature-360_Swedbank_SE>bank2ynab.bat
ERROR:
Format: SE Swedbank 2020

Error: Can't find download path: "M:\Bank Statements"
Trying default path instead:     C:\Users\stonedestroyer\Downloads
INFO:
Parsing input file:  C:\Users\stonedestroyer\Downloads\Transaktioner_2020-07-31_17-07-11.csv (format: SE Swedbank 2020)
INFO: Using encoding Windows-1252 with confidence 0.73
INFO: Using encoding Windows-1252 with confidence 0.73
INFO: Parsed 419 lines
INFO: Writing output file: C:\Users\stonedestroyer\Downloads\fixed_Transaktioner_2020-07-31_17-07-11.csv
INFO:
Done! 1 files processed.

INFO: Connecting to YNAB API...
INFO: Processing transactions...
ERROR: 404.2 - Resource not found (resource_not_found)
| 1 | E
| 2 | 4
| 3 | R
No YNAB account for transactions from SE Swedbank 2020 set!
 Pick an account (range 1 - 3): 1
INFO: Saving default account for SE Swedbank 2020...
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "bank2ynab\__main__.py", line 22, in <module>
    api.run(b2y.transaction_data)
  File "bank2ynab\ynab_api.py", line 46, in run
    budget_t_data = self.process_transactions(transaction_data)
  File "bank2ynab\ynab_api.py", line 103, in process_transactions
    budget_transactions = budget_t_data[budget_id]["transactions"]
TypeError: unhashable type: 'list'
```

**Comment by nocalla** [comment]
I'll look into that error, I don't think it's anything you did, that's an error in the API logic.

Is the "fixed" file converted correctly though?

**Comment by Stonedestroyer** [comment]
The encodings on file look wrong, some Swedish signs are gone and replaced with #. 

Example lines seem to be like
`2020-05-28,PREEM,,PREEM,49.00,`
not sure if this is correct.

**Comment by nocalla** [comment]
That example line looks to match the required format.

**Comment by Stonedestroyer** [comment]
Is there a way to fix the swedish signs? Or have it import as UTF-8.

**Comment by nocalla** [comment]
It looks like the input file is encoded as Windows-1252 according to your paste above. Is that correct?

**Comment by Stonedestroyer** [comment]
Excel opens it properly, vscode opens it wrong as well. I am not sure what
encoding it is. How would I check?

**Comment by nocalla** [comment]
On the API error above - are you using the latest version of the code? I remember fixing that error a while back, so I'm hoping your answer is no! To check encoding you can open the file with Notepad and see what the default encoding method is when you go to Save As.
