### ISSUE TITLE
IE AIB Format Recognised But 0 Lines Parsed and No Output Data

### ISSUE THREAD

**Issue by diploux** [bank2ynab/bank2ynab#364]
I've exported a CSV transaction list from AIB Bank. 

In the parsing input file line it recognises the format as "IE AIB Ireland".

The rest of the lines in Terminal look like this:

INFO: Using encoding ascii with confidence 1.0
INFO: Parsed 0 lines
INFO: No output data from this file for this bank.
INFO: 
Done! 1 files processed.

I'm using Python 3 on MacOS Catalina.

Thanks!

**Comment by nocalla** [comment]
Thanks for the report. Can you paste the first few lines of the file here please? Just to see if it's changed format since we entered it. Obviously anonymise any data!

**Comment by diploux** [comment]
Posted Account,   Posted Transactions Date, Description1, Description2, Description3, Debit   Amount, Credit Amount,Balance,Posted Currency,Transaction Type,Local Currency   Amount,Local Currency
--
[sortcode] -   [acc number],"04/08/2020","VDP-AMZN Mktp   ES*M","","","41.34",,"128354.25",EUR,"Debit","   41.34",EUR

**Comment by nocalla** [comment]
Ah! This was one of our incomplete formats actually as we didn't have the date format from the survey response! 

```
[IE AIB Ireland]
# source: survey response #16
# Transaction_Export_12.12.2012_12.12.csv
Use Regex For Filename = True
Source Filename Pattern = Transaction_Export_[0-9]{2}.[0-9]{2}.20[0-9]{2}_[0-9]{2}.[0-9]{2}
Input Columns = skip,Date,Payee,Inflow,Outflow,skip,skip
# Date Format = # unknown!
```

**Comment by nocalla** [comment]
Though it looks like they have actually updated the format since that survey. Amended lines below. I'll update the conf file. 



Input Columns = skip,Date,Payee,skip,skip,Outflow,Inflow,skip,skip,skip,skip
Date Format = %d/%m/%Y

**Comment by nocalla** [comment]
Thanks for the contribution - we were missing information. The latest Develop branch should work for you now. Let me know if it doesn't.

**Comment by diploux** [comment]
Thanks a lot - tested and working.
