### ISSUE TITLE
Error NL ING Checking 2020: IndexError when when running comparison on indicator_col for CD_flag

### ISSUE THREAD

**Issue by ferryrs** [bank2ynab/bank2ynab#365]
Dear community,

After having worked perfectly for a while. The last couple of weeks it is not working anymore. I just downloaded the latest developer code, but that does also not solve the issue.

This is the error I am getting:

```
XXX-MBP:bank2ynab-develop XXusernameXX$ python3 ./bank2ynab
INFO: 
Parsing input file:  /Users/username/Downloads/NL00INGB0000000000_06-08-2020_26-08-2020.csv (format: NL ING Checking 2020)
INFO: Using encoding ascii with confidence 1.0
INFO: Using encoding ascii with confidence 1.0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./bank2ynab/__main__.py", line 19, in <module>
    b2y.run()
  File "./bank2ynab/bank_process.py", line 382, in run
    output = bank.read_data(src_file)
  File "./bank2ynab/bank_process.py", line 126, in read_data
    row = self._cd_flag_process(row, cd_flags)
  File "./bank2ynab/bank_process.py", line 305, in _cd_flag_process
    if row[indicator_col] == outflow_flag:
IndexError: list index out of range
XXX-MBP:bank2ynab-develop XXusernameXX$ 
```

*for privacy reasons I censored my username and banking number (changed to zero's and X's).*

Please advice.

**Comment by ferryrs** [comment]
Still got this issue. How can I solve it?

**Comment by ferryrs** [comment]
Datum;"Naam / Omschrijving";"Rekening";"Tegenrekening";"Code";"Af Bij";"Bedrag (EUR)";"Mutatiesoort";"Mededelingen";"Saldo na mutatie";"Tag" |  
-- | --
20201006;"XXX NLD";"NL00INGB0000000000";"";"BA";"Af";"33 | 94";"Betaalautomaat";"Pasvolgnr: 000 05-10-2020 12:12 Transactie: XXXXX Term: XXXX Valutadatum: 06-10-2020";"1
20201006;"XXX NLD";"NL00INGB0000000000";"";"BA";"Af";"17 | 50";"Betaalautomaat";"Pasvolgnr: 000 05-10-2020 01:01 Transactie: XXXX Term: XXXX Valutadatum: 06-10-2020";"35

First three lines of the .csv file.

**Comment by nocalla** [comment]
Does it have that exact formatting?

**Comment by ferryrs** [comment]
Yes.

Editted the descriptions a bit for privacy purposes, but left the formatting fully untouched.

**Comment by nocalla** [comment]
For reference, here's the current configuration for this bank:

```
[NL ING Checking 2020]
# source: survey response #53, 20200116 
# NL04INGB0704279991_01-01-2019_11-01-2020.csv
Use Regex for Filename = True
Source Filename Pattern = NL[0-9]{2}INGB[0-9]*_[0-9]{2}-[0-9]{2}-[0-9]{4}_[0-9]{2}-[0-9]{2}-[0-9]{4}
Header Rows = 1
Footer Rows = 0
# Datum,"Naam / Omschrijving","Rekening","Tegenrekening","Code","Af Bij","Bedrag (EUR)","MutatieSoort","Mededelingen"
Input Columns = Date,Payee,skip,skip,skip,CDFlag,Inflow,skip,Memo
Date Format = %Y%m%d
Inflow or Outflow Indicator = 5,Bij,Af

It looks like we're missing two fields at the end of the row, but that shouldn't make a difference. What may make a difference is that there are actually two header rows rather than one. 

Header rows: 
```
Datum;"Naam / Omschrijving";"Rekening";"Tegenrekening";"Code";"Af Bij";"Bedrag (EUR)";"Mutatiesoort";"Mededelingen";"Saldo na mutatie";"Tag" |  
-- | --
```

**Comment by ferryrs** [comment]
I think it actually has one header row. Not sure what this is: '-- | --'. However I just did notice that there is in fact a column C (with useless info).

I just uploaded the file. Changed the file format from .csv to .xlsx to make uploading possible via GitHub. Hope this makes the situation more clear.

[NL00INGB0000000000_01-10-2020_06-10-2020.xlsx](https://github.com/bank2ynab/bank2ynab/files/5377395/NL00INGB0000000000_01-10-2020_06-10-2020.xlsx)

**Comment by nocalla** [comment]
Ah, so that "-- | --" isn't in the file at all? Okay. 

The Excel conversion seems to have done some strange things to the formatting, unfortunately, so I will just refer to your pasted data above. Does `bank2ynab` fail to produce a correctly formatted file if you use the data above?

**Comment by ferryrs** [comment]
I just noticed that there is not a 'bank2ynab.py' file anymore inside the main directory, but a .bat file instead. What is the right command to activate the program on Mac? I will test and see what it does, by using the latest download.

**Comment by SliceOLife** [comment]
I have an ING checking account as well. I'll give it a look as soon as possible.
