### ISSUE TITLE
Support "Pending" Transactions

### ISSUE THREAD

**Issue by clancychilds** [bank2ynab/bank2ynab#371]
**Describe the solution you'd like**
It looks like YNAB now supports "Pending" transactions (when a transaction is on a card, but doesn't have a date to be posted yet. Some Credit Card exports have these transactions in the export and it would be nice if they could be imported in bank2ynab as pending.
I checked the YNAB API and I don't yet see whether Pending transactions are supported by the transactions API.

**Comment by nocalla** [comment]
I don't see any information on how "Pending" transactions are classified in the API or in imports from YNAB. We'd need to get more information on how to handle these when providing files for importing to YNAB.

**Comment by nocalla** [comment]
According to the API documentation, pending files are not supported, so marking this `wontfix` for now. We can revisit this if the API is updated.
