### ISSUE TITLE
OCBC Bank Credit Card

### ISSUE THREAD

**Issue by JieqinT** [bank2ynab/bank2ynab#372]
**New bank format**
*If you're submitting something else, skip or remove this section and continue below.*
- Full name of the bank: Oversea-Chinese Banking Corporation, Limited
- Country (2-character country code): SG

**Describe the solution you'd like**
Find a way to have both OCBC statement and credit card to be recognised. 

Since I use CC more than the savings, i commented out the OCBC bank's version and used the CC primarily. Haven't read too much into your code, not sure how you're gonna differenciate the CC statements and the Savings account statements since both files uses the same format.. 

**Additional context**
Currently modified local copy of `bank2ynab.conf`. Here's my modification of the code that is working for me now. 
```
# [SG OCBC Bank]
# Use Regex For Filename = True
# Source Filename Pattern = TransactionHistory_\d{4}\d{2}\d{2}\d{6}
# Header Rows = 6
# Footer Rows = 2
# Input Columns = Date,skip,Memo,Outflow,Inflow,Payee
# Date Format = %d/%m/%Y
# Plugin = OCBC_Bank_SG

[SG OCBC Bank CC]
Use Regex For Filename = True
Source Filename Pattern = TransactionHistory_\d{4}\d{2}\d{2}\d{6}
Header Rows = 4
Footer Rows = 2
Input Columns = Date,Memo,Outflow,Inflow
Date Format = %d/%m/%Y
Plugin = OCBC_Bank_SG
```

**Comment by nocalla** [comment]
I'll add the credit card format to the config file, but unfortunately we won't have a way of differentiating the two. Thanks for the contribution.

**Comment by ExalDraen** [comment]
A few options:
* alllow users to supply a different config file on the command line, so someone can call the script with either config
* if multiple patterns match, ask the user to choose one per file. OR add some feature to inspect the file for contents
