### ISSUE TITLE
Money Dashboard support

### ISSUE THREAD

**Issue by Sinderella** [bank2ynab/bank2ynab#379]
**Is your feature request related to a problem? Please describe.**
UK banks widely support open banking APIs now and syncforynab is a bit pricey. I am currently using money dashboard to sync and obtain all of the transactions from different banks and cards. Money Dashboard allows CSV export for account(s) so it's an easy way to just export once, parse and upload.
However, the CSV format is in the following format, I can either export each account individually or manually formatting the CSV. By account, it could be the name of the accounts (credit card A, credit card B, saving account, ...).
```
"Account","Date","Original Date","Description","Original Description","Amount","Currency","Category","Budget"
```

**Describe the solution you'd like**
I am not sure if bank2ynab could support different types of account within a single file, but it'd be great if we could have that and export into multiple files.

**Describe alternatives you've considered**
We could have a script which splits the CSV file into multiple ones and then use bank2ynab to parse those into standard ones. I doubt this is difficult, but can be probably be preferred to separate the functionality.

I can provide more information if require, I didn't want to go straight up dumping formats and stuff without discussing. :)

Cheers

**Comment by torbengb** [comment]
Just a quick thought, haven't looked into details yet:

I'm thinking that bank2ynab's plugin capabilities can be used to pre-parse
the combined file - but the new thing would be that the plugin might need
to call bank2ynab again to parse each split file?

**Comment by Sinderella** [comment]
Yep, it would still need to call those files again.
Ah, I didn't realise that there's plugin capabilities in place already. I will have a look. cheers!
