### ISSUE TITLE
ERROR: 401 - API access token missing

### ISSUE THREAD

**Issue by cheesemaker7651** [bank2ynab/bank2ynab#380]
I have followed your instructions to the letter, including making sure there is a space either side of the = sign in my user_configuration.conf.template, but I am still getting "ERROR: 401 - API access token missing etc". 

```
[DEFAULT]
# Specify where you save your downloaded CSV files: 
Source Path = /Users/xyz/Documents/Transactions
YNAB API Access Token = 0ppd....MySecretNumber....87623
```

If I run the YNAB example (`curl -H "Authorization: Bearer <my ACCESS_TOKEN>" https://api.youneedabudget.com/v1/budgets`), my access token works. 

Any clues?

**Comment by torbengb** [comment]
Hi!
Make sure your edited file is named "user_configuration.conf", without the
".template" ending. Let us know if that didn't resolve the issue.

**Comment by cheesemaker7651** [comment]
Bingo! Thank you so much for putting all of this together.
