### ISSUE TITLE
Handle multiple accounts from different banks

### ISSUE THREAD

**Issue by jtpedersen** [bank2ynab/bank2ynab#383]
I made fork that is able to handle multiple accounts from different banks.

It works by: 
1. Generate a matching tree structure to the budgets on YNAB
2. The user (me) puts csv files in the folders matching the accounts
3. The script walks throug each folder in the tree and determines the bank type (json file in folder) and posts the data to the ynab api

The state is that it works for me and I think that is a nifty addition usage of bank2ynab.  I did some refactorings on various api parts to understand the code and to force it to work for this use case.

If there is any interest in getting this into mainline I can try to clean up the commits etc?

https://github.com/jtpedersen/bank2ynab/tree/multi_accounts

I wrote a bit on gitter but got no response and now I just added the different banks feature so...

**Comment by jtpedersen** [comment]
This changes the general flow of bank2ynab so the mapping between a csv file and the corresponding bank and account no longer is fixed and determined by a regex on the filename. I had a bank where i could change the filename and had mulitiple accounts and could not understand/make the default work. This is relationsship is established by the relative path to the file (for account) and meta-information for the bank identifier.

To illustrate

```
:~/src/bank2ynab$ tree imports/
imports/
└── My Budget
    ├── AL-budget
    │   └── account_info.json
    ├── AL-Helle
    │   └── account_info.json
    ├── Al-jacob
    │   └── account_info.json
    ├── AL-Jacob-Master
    │   └── account_info.json
    ├── AL-MadKontoen
    │   └── account_info.json
    ├── MidSpar-bolig
    │   └── account_info.json
    └── MidSpar-forbrug
        └── account_info.json

8 directories, 7 files
```
Where the content of account_info.json is a simple json with contents like `{"bank_id": "DK Portalbank"}` but that information is now specific for each account.

The initial structure is build by querying the ynab api for the budgets and accounts.

Any csv file put into a subfolder til when running the bank2ynab program will then be exported the YNAB and then have the file moved to a history folder, so it will not be parsed again and there is a record of what has been imported. Having this may help find errors and/or could in future be extended to ensure that each transaction is only uploaded once.

**Comment by nocalla** [comment]
As mentioned on #386, I don't think this fits with the workflow goal of the project. Marking as won't fix. Thanks again.
