### ISSUE TITLE
Option to disable save account selection for bank

### ISSUE THREAD

**Issue by FlipEverything** [bank2ynab/bank2ynab#389]
**Other feature request**

**Is your feature request related to a problem? Please describe.**
I have more than one account at the same bank. Before I import I have to delete the `ynab account id` line from the `user_configuration.conf`. If I leave it as it was, the program imports every transaction for the same account, and obviously this is wrong.

| YNAB account name | Bank type | File name |
| --- | --- | --- |
| Checking account | OTP HU | export.csv |
| Savings account | OTP HU | export.csv |
| Checking account for site 2 | OTP HU | export.csv |
| Savings account for site 2 | OTP HU | export.csv |

**Describe the solution you'd like**
The easiest solution is a variable in the `user_configuration.conf` file to disable account selection saving. I will select an account before every import.

**Describe alternatives you've considered**
It would be great if somehow (for example based on the filename) the program could differentiate between accounts.

**Comment by FlipEverything** [comment]
Thank you for the quick help! I think it will work!

**Comment by nocalla** [comment]
Thanks for contributing.

**Comment by FlipEverything** [comment]
Thank you, I tested it and works as expected!
