### ISSUE TITLE
Source Has Column Headers settings has no effect

### ISSUE THREAD

**Issue by FlipEverything** [bank2ynab/bank2ynab#390]
**Describe the bug**
In the `bank2ynab.conf` file `Source Has Column Headers` option seems to have no effect. It's set to `False` inside the `[HU OTP]` section, but it skips the first line. If I print a newline character manually to the beginning of the file, it reads all of the data as expected.

```python
[HU OTP]
Source Has Column Headers = False
```

**What did you EXPECT to happen?**
The program will read all of the rows (including the first row) from the `export.csv` file.

```bash
Parsing input file:  /Users/laci/dev/export/export.csv (format: HU OTP)
INFO: Using encoding utf-8 with confidence 0.99
INFO: Using encoding utf-8 with confidence 0.99
INFO: Parsed 3 lines
```

**What ACTUALLY happened?**
The program skipped the first line.

```bash
Parsing input file:  /Users/laci/dev/export/export.csv (format: HU OTP)
INFO: Using encoding utf-8 with confidence 0.99
INFO: Using encoding utf-8 with confidence 0.99
INFO: Parsed 2 lines
```

**What did you DO? (steps to reproduce)**
1. create `export.csv`
2. run `python3 ./bank2ynab`

**What's your software environment?**
- Script language: Python 3.9.4
- Operating system: macOS
- OS version: 11.2

**Attachments**
[export.csv](https://github.com/bank2ynab/bank2ynab/files/6458370/export.csv)
[fixed_export.csv](https://github.com/bank2ynab/bank2ynab/files/6458379/fixed_export.csv)

**Comment by FlipEverything** [comment]
As a workaround, I wrote a shell script that adds a new line to the beginning of the csv file.

**Comment by nocalla** [comment]
Ah, turns out this is a problem with a few bank formats not being updated to match the change from a boolean header row to a defined number of header rows.  Changing `Source Has Column Headers = False` to `Header Rows = 0` should work. I'll update the config.

**Comment by FlipEverything** [comment]
Thank you! I tested this too and it works just fine!
