### ISSUE TITLE
K&H HU new bank format

### ISSUE THREAD

**Issue by FlipEverything** [bank2ynab/bank2ynab#392]
**New bank format**
- Full name of the bank: K&H
- Country (2-character country code): HU
- Any special requirements: **Is there a way to swap memo columns with each other?** 

```
Source Filename Pattern = szamlatortenet_[0-9]{8}_[0-9]{8}
Use Regex for Filename = True
Source CSV Delimiter = \t
Header Rows = 1
Input Columns = Date,skip,Memo,skip,skip,skip,Payee,Inflow,skip,Memo,skip,skip,skip,skip,skip,skip,skip,skip,skip,skip,skip
Date Format = %Y.%m.%d
```

Tested and it seems to be working! Should I provide a sample csv file?

**Comment by nocalla** [comment]
A sample CSV isn't a requirement, it's just sometimes helpful for weird formats or testing.

**Comment by FlipEverything** [comment]
Thank you. What should I do to have this accepted? Also, did you see my question about the memos?

**Comment by nocalla** [comment]
The easiest thing would be to do a pull request for the updated bank2ynab.conf and I can merge that. 

Regarding the memo swap - there's not currently that facility. I think the current behaviour is to merge all memo fields?

**Comment by nocalla** [comment]
Thanks for the contribution!
