### ISSUE TITLE
Uploading transactions to YNAB silently fails

### ISSUE THREAD

**Issue by FlipEverything** [bank2ynab/bank2ynab#395]
**Describe the bug**
File processing is done, connecting to YNAB API is done, but nothing is actually imported to YNAB. No error message is shown. If I manually import the `fixed_export.csv` via YNAB web UI than it works. It was fine for 2 weeks but now it does not work.

**What did you EXPECT to happen?**
When I open YNAB there are the imported transactions.

**What ACTUALLY happened?**
The program said the upload was successful but the transactions are missing from YNAB.

**What did you DO? (steps to reproduce)**
1. create `export.csv`
2. run `python3 ./bank2ynab`

**What's your software environment?**
- Script language: Python 3.9.4
- Operating system: macOS
- OS version: 11.2

**Can you provide other helpful information?**
```python
INFO:
Parsing input file:  szamlatortenet_20000101_29991231.csv (format: HU K&H)
INFO: Using encoding utf-8 with confidence 0.99
INFO: Using encoding utf-8 with confidence 0.99
INFO: Parsed 2 lines
INFO: Writing output file: fixed_szamlatortenet_20000101_29991231.csv
INFO:
Done! 1 files processed.

INFO: Connecting to YNAB API...
INFO: Processing transactions...
INFO: Previously-saved account for HU K&H found.
INFO: Uploading transactions to YNAB...
INFO: Success!
```

**Comment by FlipEverything** [comment]
Any updates on this? Could you please help me to debug this?

**Comment by nocalla** [comment]
Hmm. This looks like a problem with account matching. Can you try opening the `user_configuration.conf` file and deleting the account ID associated with the bank? Then retry and post the output.

**Comment by FlipEverything** [comment]
It's the same. I double-checked the ID and it's correct. Sometimes it works with the exact same ID.

`ynab account id = aXXXXd87-7X4e-44Xf-89fd-dfXXXXX52a45||7XXXe409-6X99-4X10-a1f5-6e6XXXXX4e6a`

I contacted YNAB if they can help debug this from their side, but they won't:

> Thanks for letting us know about this!
> 
> Since it's not officially supported by us and importing the file directly in YNAB is working fine, you'll need to reach out to the developers over at bank2ynab about that.
> 
> Let us know if we can help with anything else!

**Comment by nocalla** [comment]
It works sometimes? That's really weird. Especially since any error message from YNAB would be returned and printed in the script's output. The transactions you're trying to upload don't already exist in YNAB, do they? Can you post some anonymised transaction lines so we can test them? I know YNAB also do have a rate limit on how often you can use the API, but it's something like 200 times per hour, so maybe it's that if it's inconsistent.

**Comment by FlipEverything** [comment]
I added the following to ynab_api.py after line 172:
```py
print(json.dumps(json.loads(post_response.text), indent=4, sort_keys=True))
```

Response:
```
INFO: Uploading transactions to YNAB...
{
    "error": {
        "detail": "data limit reached",
        "id": "403.4",
        "name": "data_limit_reached"
    }
}
INFO: Success!
```

The fun thing is that this is the first time that I run this app since my last message.

**Comment by nocalla** [comment]
Well at the very least this has highlighted a problem with our error parsing. Out of interest, how many transactions are you uploading at once?

**Comment by FlipEverything** [comment]
Somewhere between 2 and 100. Currently 8. I sent debug info about it to YNAB support.

**Comment by nocalla** [comment]
It's the wrong type of error for multiple data requests (that would be a rate limit error). This seems to be related to the transactions being uploaded. I wonder is it something to do with the length of the strings in the file or something? Do you have some sample data you can paste?

**Comment by nocalla** [comment]
Alternatively, it could be related to how we are handling the existing transaction data in YNAB. To generate the transaction ID number, we have to check against existing transactions which get downloaded each time. It's possible that this is the data limit being reached. I have transactions going back to 2015 in my budget though and haven't hit this issue. The API *does* allow for delta requests though, so we could perhaps use that functionality to store a local copy of the transaction data which only requires a partial transaction download. I don't know do we want to be storing a full transaction data file though.

**Comment by FlipEverything** [comment]
YNAB confirmed that it is likely a bug/problem on their end. Likely my budget is too big and the API is limited in a lot of ways.

>  403.4 error generally means the API request was too large for our servers to handle. We put limits in place on individual API requests to prevent abuse. It's different than being Rate Limited, which is a 429 error if you make too many requests in a short amount of time. For the 403.4 error, try reducing the size of the file you're wanting to upload. You may have success after splitting the file into two (or more) files, and uploading them via the API that way so there's fewer transactions to process at a time.

But the error parsing should be fixed. Could you please help me where can I start to debug that?

**Comment by nocalla** [comment]
Thanks for getting the response from YNAB, that's valuable information. Maybe we can automatically split the upload based on number of transactions. It would help if we knew what the threshold was for getting the error. I wonder if it is the size of the JSON rather than number of lines. 

 'm away right now so can't do a deep dive into the error code, but will take a look when I get back.

**Comment by FlipEverything** [comment]
No, the problem is with the size of the budget, not of the JSON/payload. 1 transaction works, but anything above 1 won't.

**Comment by nocalla** [comment]
Okay, in that case I think the fix would be for us to use the delta request feature and have a local copy of the budget downloaded. That way only the changed transactions since the last request will be downloaded. That's a big fix though!

**Comment by FlipEverything** [comment]
I don't think that it'll be necessary. Currently, I'm waiting for YNAB's response about the issue.

**Comment by nocalla** [comment]
Marking this as `wontfix` since the issue seems to be on YNAB's end.

**Comment by FlipEverything** [comment]
@nocalla We sorted it out... It was a tough one... Compressed, migrated the budget, deleted thousands of transactions several times and now I can use the API normally. Thank you for your help. As it turns out YNAB has a budget size restriction as well...

**Comment by nocalla** [comment]
That's great! Out of interest, do you have any hard details on the budget size limit?

**Comment by FlipEverything** [comment]
@nocalla Sadly, no... They said that I have to delete transactions until the API allows us to use the endpoint... Currently, I have 14.829 transactions in my main budget and it's still working. I hope that it will work until the end of the year when we do a fresh start. I deleted approximately 28.000 transactions to make it work.

**Comment by nocalla** [comment]
I'd better keep an eye on my transactions so!
