### ISSUE TITLE
NO Sparebank 1 VISA - no output data

### ISSUE THREAD

**Issue by nafstad** [bank2ynab/bank2ynab#396]
Hello,

I'm trying to get bank2ynab to work.
I get a CSV file from my bank, and can find it in the bank2ynab.conf.

The only thing that is different there is that the data in the CSV file is not separated with ";". They all got a column each.

So I tried to removed the `Source CSV Delimiter = ;`.

All that I get is this:

`/OversiktKonti-01.06.2021-24.06.2021.csv (format: NO Sparebank 1 VISA)`
`INFO: Using encoding UTF-8-SIG with confidence 1.0`
`INFO: Using encoding UTF-8-SIG with confidence 1.0`
`INFO: Parsed 0 lines`
`INFO: No output data from this file for this bank.`
`INFO: `
`Done! 1 files processed.`

I have installed all the requirements.

So, any suggestions?

**Comment by nocalla** [comment]
Try to open your file with Notepad and see what character separates the "columns". CSV doesn't actually have columns, but if you open it with Excel, Excel will "translate" it into columns. There *has* to be a separating character, or else it's not a C*S*V (comma separated values) file.

**Comment by nafstad** [comment]
Thanks, I can see that it is separated with that character ";".

But, I still get the same message.

**Comment by nafstad** [comment]
Here are the first few lines, if that's helps:

`Dato;Beskrivelse;Rentedato;Inn;Ut;Til konto;Fra konto;`
`"23.06.2021";"Some text";"23.06.2021";;"-30,00";"00000000000";"11111111111";`
`"23.06.2021";"Some text";"23.06.2021";;"-69,00";;"00000000000";`
`"23.06.2021";"Some text";"23.06.2021";"500,00";;"00000000000";"11111111111";`
`"22.06.2021";"Some text;"22.06.2021";;"-20,00";"00000000000";"11111111111";`
`"22.06.2021";"Some text";"22.06.2021";;"-166,68";;"00000000000";`
`"22.06.2021";"Some text";"22.06.2021";;"-178,60";;"00000000000";`

**Comment by nocalla** [comment]
Can you paste a few lines from the start of the file? As well as the  changed config lines you're using. Obviously change the amounts and payees.

**Comment by nafstad** [comment]
Posted it right before you here, and changed some of the text.

**Comment by nocalla** [comment]
`So I tried to removed the Source CSV Delimiter = ;.`

And you've restored this line in the .conf file?

**Comment by nafstad** [comment]
Yes:

`[NO Sparebank 1 VISA]`
`# source: survey response #42`
`Use Regex for Filename = True`
`Source Filename Pattern = OversiktKonti-\d{2}.\d{2}.\d{4}-\d{2}.\d{2}.\d{4}`
`# OversiktKonti-01.04.2019-05.05.2019`
`Source CSV Delimiter = ;`
`Header Rows = 1`
`Input Columns = Date,Payee,skip,Inflow,Outflow,skip,skip`
`# Dato;Beskrivelse;Rentedato;Inn;Ut;Til konto;Fra konto;`
`# "05.05.2019";"Nettbank";"05.05.2019";"994,00";;"12345678956";;`

**Comment by nocalla** [comment]
Ah, I think I see the problem - the date format is missing. Try updating your config to the following.

```
[NO Sparebank 1 VISA]
Use Regex for Filename = True
Source Filename Pattern = OversiktKonti-\d{2}.\d{2}.\d{4}-\d{2}.\d{2}.\d{4}
Source CSV Delimiter = ;
Header Rows = 1
Input Columns = Date,Payee,skip,Inflow,Outflow,skip,skip
Date Format = %d.%m.%Y
```

**Comment by nafstad** [comment]
That solved it, Thanks!

**Comment by nocalla** [comment]
I'll push a fix to the `develop` branch that will resolve this for any other users.
