### ISSUE TITLE
"Done! 0 files processed."

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#415]
**Describe the bug**
Hello Niall&co! I've been away for far too long - apologies! I have tried to run this again but I have no luck. I cannot make the tool find and import my file. It's not clear what I need to change to fix this?

**What did you EXPECT to happen?**
When I run the BAT file, I expect it to find the CSV file and import it.

**What ACTUALLY happened?**
When I run the BAT file, it immediately gives this output and is done:
```
D:\bank2ynab>bank2ynab.bat D:\meinElba_umsaetze_AT273239500000141085_suche.csv
INFO:
Done! 0 files processed.

D:\bank2ynab>
```

**What did you DO? (steps to reproduce)**
1. download a bank CSV file to `D:\`
1. download the tool to `D:\bank2ynab`
1. observe that `bank2ynab.conf` contains an entry for this CSV file name:  
  `[AT Raiffeisen Bank 2019 checking]`
1. create `user_configuration.conf`:
  `[DEFAULT]`
  `Source Path = D:\`
  `YNAB API Access Token = i-created-a-brand-new-token`
1. install python: `choco install python3`
1. install bank2ynab requirements: `pip3 install -r requirements.txt`
1. navigate to `D:\`
1. execute `bank2ynab.bat` 
1. observe the tool didn't find my CSV file.

And then
1. repeat the above with each of `origin/develop`, `origin/master`, `origin/1.4.0`

**What's your software environment?**
 - Script language: Python 3.10.2
 - Operating system: Windows 10 (brand new install)

**Comment by nocalla** [comment]
So it doesn't find the file at all? Can you try run it from the command line instead?

**Comment by nocalla** [comment]
To see if it's a bank-specific issue, can you try testing with one of the `test-data` files also?

**Comment by torbengb** [comment]
Yes it behaves as if there is no matching file. But I have triple checked
the source path.

I tried executing the command in the batch file, directly on the command
line, with the same result... (Win10 'cmd', not Powershell).

I'm not skilled enough to step through the actual code, but I would like to
add some debug statements along the way to see where it goes wrong.

**Comment by torbengb** [comment]
I will try some test files tomorrow and report back.

**Comment by nocalla** [comment]
Try navigating to the repository directory and running the bank2ynab package from the command line and see if anything is different to using the .bat file.

**Comment by torbengb** [comment]
I have edited the entry `[AT Raiffeisen Bank 2019 checking]` from:  
`Source Filename Pattern = meinelba_umsaetze_AT[0-9]{18}_suche` to
`Source Filename Pattern = meinElba_umsaetze_AT273239500000141085_suche`
and voilà, my file is now found. 

So it seems the RegEx is wrong! And indeed it is: it's looking for "meinelba" but the bank output is now "meinElba". Damn them! 😠

I will submit an update to the conf file....

**Comment by nocalla** [comment]
Cool! That's an easy fix.

**Comment by torbengb** [comment]
Yeah, but hard to find. More gray hairs......
