### ISSUE TITLE
No output file for this bank

### ISSUE THREAD

**Issue by Gravity2k** [bank2ynab/bank2ynab#432]
**Describe the bug**
Problem with running the code. It detects the right bank and format, but does not output any file. This is in the terminal

```
(DE Deutsche Kreditbank checking)
INFO:   Opening file using encoding ISO-8859-1 (confidence 0.73)
INFO: No output data from this file for this bank. (Expected 9 fields in line 9, saw 12)
ERROR:
```

**What did you EXPECT to happen?**
An output file, no error

**What ACTUALLY happened?**
See "bug"

**What did you DO? (steps to reproduce)**
1. Download File from DKB, did not change it.
2. Run the code in terminal python bank2ynab in the folder
3. Get the error
4. Write an Issue ;)

**What's your software environment?**
 - Script language: Python 3.10.9
 - Operating system: Windows
 - OS version: 10

**Can you provide other helpful information?**
I looked into the bank2ynab.conf and saw that the criteria to look for the right file are correct

```
[DE Deutsche Kreditbank checking]
*# source: Issue #132
*# 1234567890.csv
Use Regex For Filename = True
Source Filename Pattern = [0-9]{10}
Header Rows = 7
Source CSV Delimiter = ;
Input Columns = skip,Date,Memo,Payee,skip,skip,skip,Inflow,skip,skip,skip
Date Format = %d.%m.%Y
```

I wonder why it says it saw 12 fields and expected 9. It has 11 fields, Just like in "input columns" defined. So i do not know what happens here. Sry I am some kind of a newb in programming.

**Comment by nocalla** [comment]
Hi, can you paste a sample line from your transaction file? Anonymised, obviously. This will help us see what's going on. My guess is that your bank has updated its file format.
