### ISSUE TITLE
NL ING Checking 2020 works, but not when the bank web interface is set to English

### ISSUE THREAD

**Issue by DarkwaterV3** [bank2ynab/bank2ynab#448]
**Describe the bug**
All transactions are inflows when downloading a semicolon separated CSV file from Mijn ING with language set to English, converting with B2Y and importing into YNAB 4.

**What did you EXPECT to happen?**
Import without issue, with correct transactions, as the console output of bank2ynab.bat would have me believe.

**What ACTUALLY happened?**
All transactions are inflows (hah, I wish!).

**What did you DO? (steps to reproduce)**
1. First log into Mijn ING with language set to English (language choice available on login page)
2. Then download transactions as semicolon separated values (I believe this is the intended option, though that is not noted anywhere AFAIK)
3. And then run it through Bank2Ynab, it should return no errors
4. Import into YNAB (4 in my case) and all transactions should be marked as inflows, which is not actually the case for my download

**What's your software environment?**
Sorry, I believe this is not relevant for this report.

**Can you provide other helpful information?**
The problem does not occur when having the language set to Dutch. When in English mode, the 'inflow and outflow indicators' change from 'af & bij' to 'debit & credit'. I believe this is the core issue.

**Attachments**
Upon request I can provide a sample.

**Comment**
I of course leave it up to you whether to add compatibility for the English variant, or just to comment into the .conf file that the Dutch web interface is required for this to work. That is, if I'm right about the core issue.

I am just happy to have found the problem and that I can fix it myself. Many thanks and have a good day!

**Comment by nocalla** [comment]
Is the filename different too? If so, we can have a separate configuration entry. Otherwise, your suggestion that Dutch language is required is the way to go.

**Comment by DarkwaterV3** [comment]
I've just downloaded some statements in both languages and can confirm that the file name syntax is the same for both.

**Comment by nocalla** [comment]
That's a shame, we'll have to just make the note in the conf file so.

**Comment by DarkwaterV3** [comment]
You probably already thought of this, but just to be sure: can the 'inflow or outflow indicator' not be set to something along the lines of '(af,bij) OR (debit,credit)'?

**Comment by nocalla** [comment]
Short answer - no, not really without a significant rework of the Credit/Debit flag logic.
