### ISSUE TITLE
filename pattern of "BE BNP Paribas Fortis Export” matches “NL Rabobank-2018” files

### ISSUE THREAD

**Issue by ugrossek** [bank2ynab/bank2ynab#452]
The filename pattern of "BE BNP Paribas Fortis Export” matches “NL Rabobank-2018” files. This leads to parser errors for Rabobank csv files.

[BE BNP Paribas Fortis Export]
Source Filename Pattern = CSV_*

[NL Rabobank-2018]
Source Filename Pattern = CSV_A_20[0-9]{6}_[0-9]{6}

Since the BE filename pattern is evaluated before NL, we see parsing errors.

Solution 1: be more specific with the BE filename pattern
Solution 2: move the NL Rabobank-2018 entry up

**Comment by nocalla** [comment]
Well spotted, thanks for identifying the issue. These formats were added in #422. @wooter can you update the regex used in the conf file to be more specific please?

**Comment by wooter** [comment]
See #453

**Comment by nocalla** [comment]
Should be fixed in the `develop` branch. Thanks again for flagging it.
