### ISSUE TITLE
Question: two budgets with different accounts in same bank

### ISSUE THREAD

**Issue by jenseo** [bank2ynab/bank2ynab#454]
**Is your feature request related to a problem? Please describe.**
Hi there, maybe there is already support for this, if this is the case then my feature request is to improve the docs around this! :)

So, I have set up an automation that pulls two different statements from two accounts in my bank. These accounts are tied to one YNAB budget each.

When I save these two statements in my upload folder and run the script, I get the question into which account this SET should be 
imported, but I would like that each FILE should be imported into different accounts.

Is there a way to accomplish this, or do I have to separate things somehow and do the uploads separately?

Thanks a lot for a great tool, I have a feeling this will be an invaluable part of my life going forward :D

**Comment by nocalla** [comment]
Glad you're finding it useful. The way the whole tool is set up is to treat all files from the same bank the same, but if you wanted to, you could modify the .conf file to have copies of your bank that search for a specific account number in the filename. So basically pretending that they're from different banks. But that only works if your files get named differently based on account number - which you could do manually as a workaround.

**Comment by jenseo** [comment]
> Glad you're finding it useful. The way the whole tool is set up is to treat all files from the same bank the same, but if you wanted to, you could modify the .conf file to have copies of your bank that search for a specific account number in the filename. So basically pretending that they're from different banks. But that only works if your files get named differently based on account number - which you could do manually as a workaround. 

Thanks a lot for the quick reply! That sounds like a great idea, will explore it!

**Comment by jenseo** [comment]
@nocalla Btw, can I add the bank configs to my user conf as well, to make the changes future proof? Or are the bank parts not overrideable?

**Comment by nocalla** [comment]
Yeah, whatever is in the user conf should override the main conf file.
