### ISSUE TITLE
UOB SG

### ISSUE THREAD

**Issue by limdingwen** [bank2ynab/bank2ynab#458]
# Savings Account

**New bank format**
*If you're submitting something else, skip or remove this section and continue below.*
- Full name of the bank: UOB
- Country (2-character country code): SG
- Any special requirements:

*Bank format: only fill out these lines if you're comfortable with it, otherwise skip:*
*To be filled in as required. Delete fields that match default values.*
```
Source Filename Pattern = ACC_TXN_History\d{14}
Source Filename Extension = .xls
Use Regex for Filename = True
Source CSV Delimiter =
Header Rows = 8
Footer Rows = 0
Input Columns = Transaction Date,Transaction Description,Withdrawal,Deposit,Available Balance
Date Format = %d %b %Y
# (see http://strftime.org/ for date format strings)
Inflow or Outflow Indicator = Separate columns
Output Columns = Date,Payee,Category,Memo,Outflow,Inflow
Output Filename Prefix = fixed_
Plugin =
```

# Credit Card Balance

**New bank format**
*If you're submitting something else, skip or remove this section and continue below.*
- Full name of the bank: UOB
- Country (2-character country code): SG
- Any special requirements: If you see a row that contains "Previous Balance", ignore it!

*Bank format: only fill out these lines if you're comfortable with it, otherwise skip:*
*To be filled in as required. Delete fields that match default values.*
```
Source Filename Pattern = CC_TXN_History\d{14}
Source Filename Extension = .xls
Use Regex for Filename = True
Source CSV Delimiter =
Header Rows = 10
Footer Rows = 0
Input Columns = Transaction Date,Posting Date,Description,Foreign Currency Type,Transaction Amount(Foreign),Local Currency Type,Transaction Amount(Local)
Date Format = %d %b %Y
# (see http://strftime.org/ for date format strings)
Inflow or Outflow Indicator = Negative sign
Output Columns = Date,Payee,Category,Memo,Outflow,Inflow
Output Filename Prefix = fixed_
Plugin =
```

**Comment by nocalla** [comment]
I see that these files are .xls, which we don't currently support. A plugin would be required for these.

**Comment by limdingwen** [comment]
True! I'll see if I can work on it if I have the time, since it's important
to me.
