### ISSUE TITLE
YNAB API Error: Date must not be in the future or over 5 years ago (index: 0)

### ISSUE THREAD

**Issue by ThomDietrich** [bank2ynab/bank2ynab#466]
**Describe the bug**

The API does not accept the API request. This is the error provided:

```
INFO:   Sending 'transactions' data to YNAB API...
ERROR: YNAB API Error: Error 400 - Bad syntax or validation error. The request could not be understood by the API due to malformed syntax or validation errors. (Date must not be in the future or over 5 years ago (index: 0)).
```

Generated by line:

https://github.com/bank2ynab/bank2ynab/blob/323e843bdde8e2ee5e49b21aa69646c8da0c07c6/bank2ynab/api_interface.py#L42

Example for `data`:

```
{'transactions': [{'account_id': 'xxx', 'date': '2024-08-26', 'payee_name': 'xxx', 'amount': -1000000, 'memo': 'Deeds 23.08.2024, 22.03 UHR', 'category': '', 'cleared': 'cleared', 'import_id': 'YNAB:-1000000:2024-08-26:1'}, ...
```
I did verify that all dates are correct. They are all from the last couple of months.

Any idea why this happens? Can you reproduce this?

**What did you EXPECT to happen?**

**What ACTUALLY happened?**
A clear and concise description of what actually happened.

**What did you DO? (steps to reproduce)**
1. First ...
2. Then ...
3. And then ...
4. ...

**What's your software environment?**
 - Script language: Python 3.5, Python 2.7, other?
 - Operating system: Windows, Linux, MacOS?
 - OS version:

**Can you provide other helpful information?**

**Attachments**
If applicable, add sample files or screenshots to help explain your problem.

**Comment by nocalla** [comment]
Which branch are you running? And is it with the modifications you mentioned in #465?

**Comment by ThomDietrich** [comment]
Surprise, now it works. I wonder if this was a random API issue yesterday evening.
Confirmed that it's not related to #465 

Good question! I did click the link in your README which refers to the master branch. I'll check out the dev branch now.

**Comment by ThomDietrich** [comment]
Btw the dev branch changes execution. Maybe you want to add this to the README.
Main: `python bank2ynab`
Dev: `python -m bank2ynab`
