### ISSUE TITLE
Support for Danskebank [DK]

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#95]
Sourced from [andsens/ynab-csv-converter](https://github.com/andsens/ynab-csv-converter/blob/master/ynab_csv_converter/formats/danskebank.py).
Also [trahkoi/ynab-danske-csv](https://github.com/trahkoi/ynab-danske-csv).

Row format: 'date', 'text', 'amount', 'balance', 'status', 'cleared'

Unclear if header is present.

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

From Issue #21 master list

**Comment by duch11** [comment]
I would love to try to fix this, I just need to find a Customer from Danske Bank, then I'll be glad to help out :)

**Comment by nocalla** [comment]
Covered in #219 potentially.

**Comment by mkjeldsen** [comment]
Danske Bank's standard CSV download file format is _almost_ ready. It just requires three small changes (translations, really) in the headers row:

- Col 1: "Dato" -> "Date" _("Dato" translates directly to "Date")_
- Col 2: "Tekst" -> "Payee" / "Memo" _(I prefer "Payee" as it contains a payee signifier of some sorts. "Tekst" translates directly to "Text")_
- Col 3: "Bel�b" -> "Amount" _("Bel�b" is really "Beløb" with encoding issues. "Beløb" translates directly to "Amount") 

**EXAMPLE:**
`"Dato";"Tekst";"Bel�b";"Saldo";"Status";"Afstemt"` -> `"Date";"Payee";"Amount";"Saldo";"Status";"Afstemt"`

This has been tested multiple times by yours truly.
